Repository vortex-data/vortex, pull requests merged in 2025-09, with the labels that each got.

#4445 Feature: Add `eq_with_nullability_subset ` and `eq_with_nullability_superset ` and validate `extend_from_array`
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/builders/bool.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/extension.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/builders/primitive.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/builders/varbinview.rs
  vortex-dtype/src/dtype.rs
Labels: feature

#4450 Chore: Make all `ArrayBuilder`s consistent
  vortex-array/src/builders/bool.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/extension.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/lazy_null_builder.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/builders/null.rs
  vortex-array/src/builders/primitive.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/builders/varbinview.rs
Labels: chore

#4452 Chore: `ArrayBuilder` refactor
  encodings/sparse/src/canonical.rs
  fuzz/src/array/take.rs
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/arrays/fixed_size_list/tests/nested.rs
  vortex-array/src/builders/bool.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/extension.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/builders/null.rs
  vortex-array/src/builders/primitive.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/builders/tests.rs
  vortex-array/src/builders/varbinview.rs
  vortex-layout/src/layouts/zoned/builder.rs
  vortex-scalar/src/scalar.rs
  vortex-scan/src/tests/loom.rs
Labels: chore

#4463 chore(deps): Update `tracing-subscriber`
  Cargo.toml
Labels: chore

#4473 Feature: add `to_canonical` to `ArrayBuilder`
  encodings/dict/src/array.rs
  encodings/fsst/src/canonical.rs
  encodings/sparse/src/canonical.rs
  vortex-array/src/arrays/chunked/decode.rs
  vortex-array/src/builders/bool.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/extension.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/builders/null.rs
  vortex-array/src/builders/primitive.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/builders/tests.rs
  vortex-array/src/builders/varbinview.rs
  vortex-array/src/canonical.rs
Labels: feature

#4477 chore: `#[inline]` fns vortex-array
  vortex-array/src/array/mod.rs
  vortex-array/src/iter.rs
  vortex-array/src/metadata.rs
  vortex-array/src/partial_ord.rs
  vortex-array/src/patches.rs
  vortex-array/src/validity.rs
Labels: chore

#4386 feat: VortexDataset.get_fragments yields one fragment per split
  vortex-file/src/file.rs
  vortex-python/python/vortex/_lib/dataset.pyi
  vortex-python/python/vortex/_lib/file.pyi
  vortex-python/python/vortex/arrays.py
  vortex-python/python/vortex/dataset.py
  vortex-python/python/vortex/file.py
  vortex-python/python/vortex/substrait.py
  vortex-python/src/dataset.rs
  vortex-python/src/file.rs
  vortex-python/src/io.rs
  vortex-python/test/test_dataset.py
  vortex-scan/src/split_by.rs
Labels: feature

#4486 chore: `#[inline]` fns vortex-dtype
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/nullability.rs
  vortex-dtype/src/ptype.rs
  vortex-mask/src/lib.rs
Labels: chore

#4464 Dispatch each I/O request
  vortex-file/src/driver.rs
  vortex-file/src/generic.rs
  vortex-io/src/dispatcher/mod.rs
Labels: fix

#4494 Remove evaluations, use MaskFuture
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/partitioned.rs
  vortex-layout/src/layouts/row_idx/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/reader.rs
  vortex-scan/src/tasks.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: performance

#4498 chore[ci]: tpch-10 on ci action
  .github/workflows/bench-pr.yml
  .github/workflows/sql-benchmarks.yml
  scripts/compare-benchmark-jsons.py
Labels: chore

#4509 Allow bench results to collapse in GH comment
  .github/workflows/sql-benchmarks.yml
Labels: chore

#4512 feat: Constant compression for strings
  vortex-btrblocks/src/string.rs
Labels: feature

#4517 chore[ci]: make perf script less wordy
  scripts/compare-benchmark-jsons.py
Labels: chore

#4511 fix: teach zstd to include correct validity when decompressing utf8
  Cargo.lock
  encodings/zstd/Cargo.toml
  encodings/zstd/src/array.rs
  encodings/zstd/src/test.rs
Labels: fix

#4530 fix: fix deserialization bug in pco
  encodings/pco/src/serde.rs
  encodings/pco/src/test.rs
  vortex-error/src/lib.rs
Labels: fix

#4520 Add a Vortex runtime abstraction
  Cargo.lock
  Cargo.toml
  vortex-io/Cargo.toml
  vortex-io/src/lib.rs
  vortex-io/src/runtime/current.rs
  vortex-io/src/runtime/handle.rs
  vortex-io/src/runtime/mod.rs
  vortex-io/src/runtime/multi.rs
  vortex-io/src/runtime/single.rs
  vortex-io/src/runtime/smol.rs
  vortex-io/src/runtime/tokio.rs
  vortex-io/src/runtime/wasm.rs
Labels: feature

#4536 cancelled sequence futures should remove their wakers
  vortex-layout/src/sequence.rs
Labels: fix

#4499 feat: New vx inspect tool
  Cargo.lock
  vortex-tui/Cargo.toml
  vortex-tui/README.md
  vortex-tui/src/inspect.rs
  vortex-tui/src/main.rs
  vortex-tui/src/segments.rs
Labels: feature

#4542 fix: Correctly handle slicing RunEnd arrays where slice end aligns with run end
  encodings/runend/src/arrow.rs
  encodings/runend/src/ops.rs
Labels: fix

#4541 Feature: Add `FixedSizeList` fuzzing support
  fuzz/src/array/compare.rs
  fuzz/src/array/filter.rs
  fuzz/src/array/mod.rs
  fuzz/src/array/search_sorted.rs
  fuzz/src/array/slice.rs
  fuzz/src/array/sort.rs
  fuzz/src/array/take.rs
  vortex-array/src/arrow/convert.rs
Labels: feature

#4540 File I/O abstraction for new runtimes
  Cargo.lock
  Cargo.toml
  vortex-io/Cargo.toml
  vortex-io/src/file/buffer.rs
  vortex-io/src/file/driver.rs
  vortex-io/src/file/mod.rs
  vortex-io/src/file/object_store.rs
  vortex-io/src/file/request.rs
  vortex-io/src/file/source.rs
  vortex-io/src/file/std_file.rs
  vortex-io/src/kanal_ext.rs
  vortex-io/src/lib.rs
  vortex-io/src/limit.rs
  vortex-io/src/runtime/handle.rs
  vortex-io/src/runtime/mod.rs
  vortex-io/src/runtime/single.rs
  vortex-io/src/runtime/smol.rs
  vortex-io/src/runtime/tokio.rs
  vortex-io/src/runtime/wasm.rs
Labels: feature

#4545 Feature: Implementation of `ConstantArray` and `SparseArray` canonicalize for `FixedSizeList`
  encodings/sparse/src/canonical.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/canonical.rs
Labels: feature

#4546 Fix: IsSortedKernel can return unknown, fix IsSorted for DictArray
  encodings/dict/src/compute/is_sorted.rs
  encodings/runend/src/compute/is_sorted.rs
  vortex-array/src/arrays/bool/compute/is_sorted.rs
  vortex-array/src/arrays/chunked/compute/is_sorted.rs
  vortex-array/src/arrays/decimal/compute/is_sorted.rs
  vortex-array/src/arrays/extension/compute/mod.rs
  vortex-array/src/arrays/list/compute/mod.rs
  vortex-array/src/arrays/primitive/compute/is_sorted.rs
  vortex-array/src/arrays/varbin/compute/is_sorted.rs
  vortex-array/src/arrays/varbinview/compute/is_sorted.rs
  vortex-array/src/compute/is_constant.rs
  vortex-array/src/compute/is_sorted.rs
  vortex-array/src/stats/array.rs
Labels: fix

#4550 fix: default to no explicit setting of cache_metadata
  vortex-python/python/vortex/dataset.py
Labels: fix

#4560 Fix: Don't pushdown binary numeric operations into dict arrays
  encodings/dict/src/compute/binary_numeric.rs
  encodings/dict/src/compute/mod.rs
  vortex-array/src/compute/numeric.rs
Labels: fix

#4575 Make `FieldName` an actual type an not just an alias
  vortex-array/src/array/display/mod.rs
  vortex-array/src/arrays/chunked/decode.rs
  vortex-array/src/arrays/struct_/compute/cast.rs
  vortex-array/src/arrays/struct_/compute/mod.rs
  vortex-array/src/arrays/validation_tests.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/compute/conformance/cast.rs
  vortex-dtype/src/arbitrary.rs
  vortex-dtype/src/field.rs
  vortex-dtype/src/field_names.rs
  vortex-dtype/src/serde/flatbuffers/project.rs
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/transform/partition.rs
  vortex-ffi/src/struct_fields.rs
  vortex-file/src/tests.rs
  vortex-layout/src/layout.rs
  vortex-layout/src/layouts/compact.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
  vortex-python/src/dataset.rs
  vortex-python/src/dtype/factory.rs
  vortex-python/src/file.rs
  vortex-python/src/scalar/factory.rs
  vortex-scalar/src/display.rs
  vortex-scalar/src/struct_.rs
  vortex-tui/src/browse/ui/segments.rs
Labels: feature

#4578 performance: Avoid intersecting ranges multiple times in scan
  vortex-scan/src/lib.rs
Labels: performance

#4579 Fix: simplify dict array compute functions and report correct dictarray dtype now that codes and values don't have same nullability
  encodings/dict/src/array.rs
  encodings/dict/src/compute/cast.rs
  encodings/dict/src/compute/mod.rs
  encodings/dict/src/ops.rs
Labels: chore, fix

#4580 Add results to vortex-bench
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/bin/compress.rs
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/bin/random_access.rs
  bench-vortex/src/compress/bench.rs
  bench-vortex/src/datasets/data_downloads.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/datasets/struct_list_of_ints.rs
  bench-vortex/src/datasets/taxi_data.rs
  bench-vortex/src/datasets/tpch_l_comment.rs
  bench-vortex/src/public_bi.rs
  bench-vortex/src/statpopgen/download_vcf.rs
  bench-vortex/src/statpopgen/statpopgen_benchmark.rs
  bench-vortex/src/utils/file_utils.rs
  bench-vortex/src/utils/runtime.rs
Labels: chore

#4624 Convert handles to hold weak reference to their executor
  .github/workflows/ci.yml
  Cargo.lock
  vortex-file/src/writer.rs
  vortex-io/src/runtime/blocking.rs
  vortex-io/src/runtime/current.rs
  vortex-io/src/runtime/handle.rs
  vortex-io/src/runtime/mod.rs
  vortex-io/src/runtime/single.rs
  vortex-io/src/runtime/smol.rs
  vortex-io/src/runtime/tests.rs
  vortex-io/src/runtime/tokio.rs
  vortex-io/src/runtime/wasm.rs
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/dict/reader.rs
Labels: fix

#4638 Support hive-style partitioning in DF
  Cargo.lock
  vortex-datafusion/Cargo.toml
  vortex-datafusion/src/persistent/format.rs
  vortex-datafusion/src/persistent/sink.rs
Labels: feature

#4643 Minor ScaleValue refactoring
  vortex-scalar/src/scalar_value.rs
Labels: chore

#4644 Inline some scalar code
  vortex-dtype/src/struct_.rs
  vortex-scalar/src/pvalue.rs
  vortex-scalar/src/scalar_value.rs
  vortex-scalar/src/struct_.rs
Labels: performance

#4617 Chore: add `uv sync --all-packages` in `check.sh`
  vortex-python/check.sh
Labels: chore

#4650 Explicitly register wall kernels in compute vtables in benchmarks
  encodings/alp/benches/alp_compress.rs
  encodings/dict/benches/chunked_dict_array_builder.rs
  encodings/dict/benches/dict_compare.rs
  encodings/dict/benches/dict_compress.rs
  encodings/dict/benches/dict_mask.rs
  encodings/fastlanes/benches/bitpacking_decompress_selection.rs
  encodings/fastlanes/benches/bitpacking_take.rs
  encodings/fastlanes/benches/canonicalize_bench.rs
  encodings/fastlanes/benches/compute_between.rs
  encodings/fastlanes/benches/pipeline_bitpacking.rs
  encodings/fastlanes/benches/pipeline_bitpacking_compare_scalar.rs
  encodings/fastlanes/benches/pipeline_bitpacking_kernel.rs
  encodings/fastlanes/benches/pipeline_for.rs
  encodings/fsst/benches/fsst_compress.rs
  encodings/runend/benches/run_end_compress.rs
  encodings/runend/benches/run_end_filter.rs
  encodings/runend/benches/run_end_null_count.rs
  vortex-array/src/arrow/compute/mod.rs
  vortex-array/src/arrow/compute/to_arrow/mod.rs
  vortex-array/src/arrow/mod.rs
  vortex-array/src/compute/between.rs
  vortex-array/src/compute/boolean.rs
  vortex-array/src/compute/cast.rs
  vortex-array/src/compute/compare.rs
  vortex-array/src/compute/fill_null.rs
  vortex-array/src/compute/filter.rs
  vortex-array/src/compute/invert.rs
  vortex-array/src/compute/is_constant.rs
  vortex-array/src/compute/is_sorted.rs
  vortex-array/src/compute/like.rs
  vortex-array/src/compute/list_contains.rs
  vortex-array/src/compute/mask.rs
  vortex-array/src/compute/min_max.rs
  vortex-array/src/compute/mod.rs
  vortex-array/src/compute/nan_count.rs
  vortex-array/src/compute/numeric.rs
  vortex-array/src/compute/sum.rs
  vortex-array/src/compute/take.rs
  vortex-array/src/compute/zip.rs
Labels: feature

#4653 feat: is_sorted for sequence array
  encodings/sequence/src/compute/is_sorted.rs
  encodings/sequence/src/compute/mod.rs
Labels: feature

#4577 Bump DataFusion to 50 and arrow to 56
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/arrow/convert.rs
  vortex-datafusion/Cargo.toml
  vortex-datafusion/src/convert/exprs.rs
  vortex-datafusion/src/persistent/opener.rs
  vortex-datafusion/src/persistent/source.rs
  vortex-dtype/src/arrow.rs
Labels: feature

#4588 feat: fastlanes rle
  Cargo.lock
  Cargo.toml
  encodings/fastlanes/Cargo.toml
  encodings/fastlanes/benches/pipeline_rle.rs
  encodings/fastlanes/goldenfiles/rle.metadata
  encodings/fastlanes/src/lib.rs
  encodings/fastlanes/src/rle/compress.rs
  encodings/fastlanes/src/rle/mod.rs
  encodings/fastlanes/src/rle/ops.rs
  encodings/fastlanes/src/rle/serde.rs
Labels: feature

#4654 feat: take for sequence array
  encodings/sequence/src/compute/mod.rs
  encodings/sequence/src/compute/take.rs
  vortex-buffer/src/trusted_len.rs
Labels: feature

#4674 Revert "feat: take for sequence array"
  encodings/sequence/src/compute/mod.rs
  encodings/sequence/src/compute/take.rs
  vortex-buffer/src/trusted_len.rs
Labels: fix

#4673 Remove local path optimization for object store
  vortex-file/src/open.rs
Labels: fix

#4684 Fix: dict bool canonical preserves nullability
  encodings/dict/src/canonical.rs
Labels: fix

#4657 dict layout options to have u16 max size
  vortex-layout/src/layouts/dict/writer.rs
Labels: chore

#4705 feat: allow for linking DuckDB debug build
  vortex-duckdb/README.md
  vortex-duckdb/build.rs
Labels: feature

#4690 Rename functions in SelectExpr to make API clearer
  Cargo.lock
  vortex-dtype/src/struct_.rs
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/transform/remove_select.rs
  vortex-expr/src/traversal/references.rs
  vortex-scalar/src/struct_.rs
Labels: feature

#4713 Chore: Some small test fixes
  encodings/pco/src/test.rs
  vortex-array/src/arrays/bool/ops.rs
  vortex-array/src/arrays/list/compute/is_constant.rs
  vortex-buffer/src/buffer.rs
Labels: chore

#4709 Add serde feature to buffers and expose it externally
  Cargo.lock
  vortex-buffer/Cargo.toml
  vortex-buffer/src/lib.rs
  vortex-buffer/src/serde.rs
  vortex-expr/Cargo.toml
  vortex/Cargo.toml
Labels: feature

#4718 chore: use DuckDB debug build in `Rust tests (sanitizer)`
  .github/workflows/ci.yml
Labels: chore

#4723 chore: clarify row count assertion
  bench-vortex/src/benchmark_driver.rs
Labels: chore

#4708 Feature: `ListViewArray`
  encodings/sparse/src/canonical.rs
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/arrays/fixed_size_list/mod.rs
  vortex-array/src/arrays/fixed_size_list/vtable/serde.rs
  vortex-array/src/arrays/list/compute/take.rs
  vortex-array/src/arrays/list/mod.rs
  vortex-array/src/arrays/listview/mod.rs
  vortex-array/src/arrays/listview/tests/basic.rs
  vortex-array/src/arrays/listview/tests/mod.rs
  vortex-array/src/arrays/listview/tests/nullability.rs
  vortex-array/src/arrays/listview/tests/slice.rs
  vortex-array/src/arrays/listview/tests/validate.rs
  vortex-array/src/arrays/listview/vtable/array.rs
  vortex-array/src/arrays/listview/vtable/canonical.rs
  vortex-array/src/arrays/listview/vtable/mod.rs
  vortex-array/src/arrays/listview/vtable/operations.rs
  vortex-array/src/arrays/listview/vtable/serde.rs
  vortex-array/src/arrays/listview/vtable/validity.rs
  vortex-array/src/arrays/listview/vtable/visitor.rs
  vortex-array/src/arrays/mod.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/canonical.rs
  vortex-array/src/lib.rs
  vortex-array/src/offset.rs
Labels: feature

#4741 expose row_block_size in WriteStrategy
  vortex-file/src/strategy.rs
Labels: chore

#4619 Buffer more data in object store writer
  vortex-io/src/object_store.rs
Labels: performance

#4746 fix[array]: nested Operator format fix
  encodings/fastlanes/src/bitpacking/operator/aligned_kernel.rs
  vortex-array/src/operator/display.rs
  vortex-array/src/operator/mod.rs
  vortex-array/src/pipeline/operator/mod.rs
  vortex-duckdb/src/exporter/fixed_size_list.rs
  vortex-duckdb/src/exporter/list.rs
Labels: fix

#4740 Pipeline row selection
  encodings/fastlanes/src/bitpacking/operator/aligned_kernel.rs
  encodings/fastlanes/src/bitpacking/operator/mod.rs
  encodings/fastlanes/src/for/pipeline.rs
  encodings/fsst/src/operator.rs
  encodings/sequence/src/array.rs
  encodings/sequence/src/operator.rs
  vortex-array/src/arrays/constant/operator.rs
  vortex-array/src/arrays/primitive/operator.rs
  vortex-array/src/arrays/struct_/operator.rs
  vortex-array/src/canonical.rs
  vortex-array/src/operator/compare.rs
  vortex-array/src/operator/filter.rs
  vortex-array/src/operator/getitem.rs
  vortex-array/src/operator/metrics.rs
  vortex-array/src/operator/mod.rs
  vortex-array/src/operator/slice.rs
  vortex-array/src/pipeline/bits/view.rs
  vortex-array/src/pipeline/mod.rs
  vortex-array/src/pipeline/operator/input.rs
  vortex-array/src/pipeline/operator/mod.rs
  vortex-array/src/pipeline/row_selection.rs
  vortex-array/src/pipeline/types.rs
  vortex-array/src/pipeline/vec.rs
  vortex-array/src/pipeline/view.rs
  vortex-expr/src/exprs/between.rs
  vortex-expr/src/exprs/literal.rs
Labels: chore

#4761 Unpin nextest version
  .github/workflows/ci.yml
Labels: chore

#4769 Display predicate SQL in datafusion TreeRender
  vortex-datafusion/src/persistent/source.rs
Labels: chore

#4766 disallow changing builder size with set_validity
  vortex-array/src/builders/bool.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/extension.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/listview.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/builders/null.rs
  vortex-array/src/builders/primitive.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/builders/varbinview.rs
Labels: chore

#4783 feat[fuzz]: support slow comparison using `make_comparator` for fallback arrow compare
  vortex-array/src/arrow/datum.rs
  vortex-array/src/compute/compare.rs
  vortex-dtype/src/dtype.rs
Labels: feature

#4786 Propegate panic from tokio async code correctly
  vortex-error/src/lib.rs
Labels: chore

#4793 feat[dtype]: Rename and move `ScalarType` ->`NativeDType`, scalar -> dtype
  Cargo.lock
  encodings/alp/src/alp/compress.rs
  encodings/alp/src/alp/compute/between.rs
  vortex-dtype/Cargo.toml
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/lib.rs
  vortex-dtype/src/native_dtype.rs
  vortex-dtype/src/ptype.rs
  vortex-scalar/src/lib.rs
  vortex-scalar/src/scalar.rs
  vortex-scalar/src/scalar_value.rs
Labels: feature

#4796 Fix typo in parca config
  .github/workflows/bench.yml
Labels: chore

#4788 fix[duckdb]: handle dict and null correctly
  vortex-dtype/src/dtype.rs
  vortex-duckdb/build.rs
  vortex-duckdb/cpp/include/duckdb_vx.h
  vortex-duckdb/cpp/include/duckdb_vx/value.h
  vortex-duckdb/cpp/value.cpp
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/duckdb/logical_type.rs
  vortex-duckdb/src/duckdb/value.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/exporter/all_invalid.rs
  vortex-duckdb/src/exporter/bool.rs
  vortex-duckdb/src/exporter/cache.rs
  vortex-duckdb/src/exporter/constant.rs
  vortex-duckdb/src/exporter/decimal.rs
  vortex-duckdb/src/exporter/dict.rs
  vortex-duckdb/src/exporter/fixed_size_list.rs
  vortex-duckdb/src/exporter/list.rs
  vortex-duckdb/src/exporter/mod.rs
  vortex-duckdb/src/exporter/run_end.rs
  vortex-duckdb/src/exporter/validity.rs
  vortex-duckdb/src/exporter/varbinview.rs
Labels: fix

#4785 Initial version of Masked encoding
  vortex-array/src/arrays/constant/compute/take.rs
  vortex-array/src/arrays/masked/canonical.rs
  vortex-array/src/arrays/masked/compute/compare.rs
  vortex-array/src/arrays/masked/compute/filter.rs
  vortex-array/src/arrays/masked/compute/mask.rs
  vortex-array/src/arrays/masked/compute/mod.rs
  vortex-array/src/arrays/masked/compute/take.rs
  vortex-array/src/arrays/masked/mod.rs
  vortex-array/src/arrays/masked/serde.rs
  vortex-array/src/arrays/mod.rs
  vortex-array/src/context.rs
  vortex-array/src/lib.rs
  vortex-btrblocks/src/float.rs
  vortex-btrblocks/src/integer.rs
  vortex-btrblocks/src/string.rs
  vortex-mask/src/bitops.rs
Labels: feature
