Repository vortex-data/vortex, pull requests merged in 2025-10, with the labels that each got.

#4801 [chore] update README.md with more citations
  README.md
Labels: chore

#4811 chore[bench]: add `--explain` and `--explain-analyze` flags
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/bin/query_bench.rs
Labels: chore

#4813 fix[encodings]: fix visit_children on sliced PCO/ZSTD encoded arrays
  encodings/pco/src/serde.rs
  encodings/zstd/src/serde.rs
  encodings/zstd/src/test.rs
Labels: fix

#4812 perf[duckdb]: zero-copy decimal exporter
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/duckdb/logical_type.rs
  vortex-duckdb/src/exporter/decimal.rs
  vortex-duckdb/src/exporter/list.rs
Labels: performance

#4823 perf[array]: don't delete filters
  vortex-duckdb/src/scan.rs
Labels: performance

#4824 ci: add helpful remarks to filter benchmark results
  scripts/compare-benchmark-jsons.py
Labels: chore

#4826 perf[duckdb]: use a single external data/vector buffer per exporter
  vortex-duckdb/build.rs
  vortex-duckdb/cpp/include/duckdb_vx.h
  vortex-duckdb/cpp/include/duckdb_vx/vector.h
  vortex-duckdb/cpp/include/duckdb_vx/vector_buffer.h
  vortex-duckdb/cpp/include/duckdb_vx/vector_buffer.hpp
  vortex-duckdb/cpp/vector.cpp
  vortex-duckdb/cpp/vector_buffer.cpp
  vortex-duckdb/src/duckdb/mod.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/duckdb/vector_buffer.rs
  vortex-duckdb/src/exporter/decimal.rs
  vortex-duckdb/src/exporter/primitive.rs
  vortex-duckdb/src/exporter/varbinview.rs
Labels: performance

#4819 Feature: add listview rebuild + cleanup
  vortex-array/src/arrays/listview/array.rs
  vortex-array/src/arrays/listview/compute/filter.rs
  vortex-array/src/arrays/listview/compute/is_constant.rs
  vortex-array/src/arrays/listview/compute/take.rs
  vortex-array/src/arrays/listview/mod.rs
  vortex-array/src/arrays/listview/rebuild.rs
  vortex-array/src/arrays/listview/tests/operations.rs
  vortex-array/src/builders/listview.rs
Labels: feature, chore

#4828 feat: FineWeb as a benchmark dataset
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/fineweb/mod.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/tpch/tpch_benchmark.rs
Labels: feature

#4787 Upgrade to DF 50.1.0
  Cargo.lock
Labels: chore

#4831 Use DataFusion's FilePruner to prune files based on stats and partition values
  Cargo.lock
  Cargo.toml
  vortex-datafusion/Cargo.toml
  vortex-datafusion/src/persistent/opener.rs
Labels: performance

#4834 revert divan codspeed compat to v3
  Cargo.lock
  Cargo.toml
Labels: chore

#4839 feat[gpu]: dict masked take kernel
  Cargo.lock
  vortex-gpu/Cargo.toml
  vortex-gpu/kernels/dict_take.cu
  vortex-gpu/src/take.rs
Labels: feature

#4836 Use the original DataFusion provided predicate to dynamically prune files
  vortex-datafusion/src/persistent/opener.rs
  vortex-datafusion/src/persistent/source.rs
Labels: feature

#4835 chore: Simplify stats truncation, optimise take function stats inheritance
  encodings/fastlanes/src/for/compress.rs
  vortex-array/src/compute/take.rs
  vortex-array/src/stats/array.rs
  vortex-array/src/stats/stats_set.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/zoned/builder.rs
Labels: chore

#4846 actually
  vortex-array/src/arrays/assertions.rs
Labels: chore

#4849 feat: auto-enable tsan for sanitizer builds
  vortex-duckdb/README.md
  vortex-duckdb/build.rs
Labels: feature

#4859 Chore: Revert codspeed to 3.0.5
  Cargo.lock
  Cargo.toml
Labels: chore

#4865 chore: drop unused patches `search_sorted` fn
  vortex-array/src/patches.rs
Labels: chore

#4827 varbinview compact to zero copy whenever possible
  vortex-array/src/arrays/varbinview/binary_view.rs
  vortex-array/src/arrays/varbinview/compact.rs
  vortex-array/src/arrays/varbinview/mod.rs
  vortex-array/src/builders/varbinview.rs
  vortex-array/src/compute/zip.rs
Labels: performance

#4863 faster StructFields::find
  vortex-dtype/src/struct_.rs
Labels: performance

#4867 wider tables in compress bench
  bench-vortex/src/bin/compress.rs
Labels: chore

#4866 Minor simplification of the serde dependency
  Cargo.lock
  Cargo.toml
  vortex-array/Cargo.toml
  vortex-array/src/patches.rs
  vortex-buffer/Cargo.toml
  vortex-buffer/src/serde.rs
  vortex-dtype/src/serde/mod.rs
  vortex-dtype/src/serde/serde.rs
Labels: chore

#4870 Revert "chore(deps): update python docker tag"
  .github/workflows/publish.yml
  .python-version
Labels: chore

#4857 feat[gpu]: for kernel and framework for running pipeline
  .github/workflows/ci.yml
  Cargo.lock
  vortex-gpu/.gitignore
  vortex-gpu/Cargo.toml
  vortex-gpu/benches/gpu_bitunpack.rs
  vortex-gpu/kernels/for.cu
  vortex-gpu/src/bit_unpack.rs
  vortex-gpu/src/for_.rs
  vortex-gpu/src/lib.rs
  vortex-gpu/src/take.rs
  vortex-gpu/src/task.rs
Labels: feature

#4850 fix[gpu]: u8, u16, u64 bitpack
  fls-gpu-kernel-gen/src/bit_unpack.rs
  vortex-gpu/src/bit_unpack.rs
Labels: fix

#4877 cheaper StructArray::clone
  vortex-array/src/array/display/mod.rs
  vortex-array/src/arrays/struct_/array.rs
  vortex-array/src/arrays/struct_/compute/cast.rs
  vortex-array/src/arrays/struct_/compute/mask.rs
  vortex-array/src/arrays/struct_/compute/mod.rs
  vortex-array/src/arrays/struct_/vtable/pipeline.rs
  vortex-array/src/arrays/struct_/vtable/serde.rs
  vortex-array/src/arrays/struct_/vtable/visitor.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/builders/struct_.rs
  vortex-btrblocks/src/lib.rs
  vortex-expr/src/exprs/merge.rs
  vortex-layout/src/layouts/file_stats.rs
  vortex-layout/src/layouts/struct_/writer.rs
Labels: performance

#4885 Yet another attempt at stopping automated python version updates
  renovate.json
Labels: chore
