Repository vortex-data/vortex, pull requests merged in 2025-05, with the labels that each got.

#3204 feat: partition scans in DuckDB Vortex extension
  duckdb-vortex/CMakeLists.txt
  duckdb-vortex/src/include/vortex.hpp
  duckdb-vortex/src/include/vortex_error.hpp
  duckdb-vortex/src/include/vortex_layout_reader.hpp
  duckdb-vortex/src/vortex_scan.cpp
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/file.rs
Labels: benchmark-sql

#3319 Publishing 16
  .github/workflows/publish.yml
Labels: chore

#3322 Fix Autolabeler
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
Labels: bug, chore

#3295 break: minimum Python 3.11
  .github/workflows/ci.yml
  .github/workflows/labels.yml
  .github/workflows/publish.yml
  .python-version
  docs/pyproject.toml
  pyproject.toml
  pyvortex/Cargo.toml
  pyvortex/pyproject.toml
  scripts/compare-benchmark-jsons.py
  uv.lock
Labels: break

#3324 feat: add is_null expression
  Cargo.lock
  vortex-expr/Cargo.toml
  vortex-expr/src/is_null.rs
  vortex-expr/src/lib.rs
  vortex-proto/proto/expr.proto
  vortex-proto/src/generated/vortex.expr.rs
Labels: feature

#3326 chore: Update README, CONTRIBUTING & STYLE guides
  CONTRIBUTING.md
  README.md
  STYLE.md
Labels: chore

#3328 Update python package
  README.md
  docs/guides/python-integrations.md
  docs/quickstart/python.rst
Labels: chore

#3325 chore: Enforce usage of parking_lot
  .cargo/config.toml
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  clippy.toml
  pyvortex/Cargo.toml
  pyvortex/src/iter/mod.rs
  pyvortex/src/registry.rs
  vortex-array/src/compute/mod.rs
  vortex-array/src/context.rs
  vortex-file/Cargo.toml
  vortex-file/src/generic.rs
  vortex-file/src/segments/cache.rs
  vortex-jni/Cargo.toml
  vortex-jni/src/file.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/filter.rs
  vortex-layout/src/layouts/stats/reader.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-metrics/Cargo.toml
  vortex-metrics/src/lib.rs
Labels: chore

#3303 perf: in vortex->duckdb conversion use as constant
  vortex-duckdb/src/convert/array/array_ref.rs
Labels: performance

#3286 feat[duckdb]: add s3 duckdb benchmarks
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/tpch/duckdb.rs
  duckdb-vortex/CMakeLists.txt
  duckdb-vortex/Makefile
  duckdb-vortex/extension_config.cmake
  duckdb-vortex/src/vortex_extension.cpp
Labels: feature, do not merge

#3335 fix: Evaluate IsNull child first
  vortex-expr/src/is_null.rs
Labels: bug

#3334 duckdb in s3 follow up nits
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/datasets/tpch_l_comment.rs
  bench-vortex/src/engines/ddb/mod.rs
Labels: chore

#3336 fix: duckdb tls on linux machine as default
  .github/workflows/bench-pr.yml
  .github/workflows/sql-benchmarks.yml
  duckdb-vortex/Makefile
Labels: bug

#3331 feat: Layout VTable
  Cargo.lock
  vortex-array/src/encoding.rs
  vortex-array/src/vtable/mod.rs
  vortex-buffer/src/const.rs
  vortex-datafusion/src/persistent/cache.rs
  vortex-dtype/src/field_mask.rs
  vortex-file/src/file.rs
  vortex-file/src/footer/mod.rs
  vortex-file/src/lib.rs
  vortex-file/src/strategy.rs
  vortex-layout/Cargo.toml
  vortex-layout/src/aliases.rs
  vortex-layout/src/children.rs
  vortex-layout/src/context.rs
  vortex-layout/src/data.rs
  vortex-layout/src/encoding.rs
  vortex-layout/src/flatbuffers.rs
  vortex-layout/src/layout.rs
  vortex-layout/src/layouts/chunked/eval_expr.rs
  vortex-layout/src/layouts/chunked/mod.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/chunked/writer.rs
  vortex-layout/src/layouts/dict/eval_expr.rs
  vortex-layout/src/layouts/dict/mod.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/dict/writer/repeating.rs
  vortex-layout/src/layouts/file_stats.rs
  vortex-layout/src/layouts/filter.rs
  vortex-layout/src/layouts/flat/eval_expr.rs
  vortex-layout/src/layouts/flat/mod.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/mod.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-layout/src/layouts/stats/mod.rs
  vortex-layout/src/layouts/stats/reader.rs
  vortex-layout/src/layouts/struct_/eval_expr.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
  vortex-layout/src/lib.rs
  vortex-layout/src/reader.rs
  vortex-layout/src/scan/mod.rs
  vortex-layout/src/scan/split_by.rs
  vortex-layout/src/strategy.rs
  vortex-layout/src/vtable.rs
  vortex-layout/src/writer.rs
  vortex-tui/src/browse/app.rs
  vortex-tui/src/browse/ui/layouts.rs
  vortex-tui/src/browse/ui/segments.rs
  vortex-tui/src/segments.rs
Labels: feature

#3343 Cache FSST compressor for running compare
  encodings/fsst/src/array.rs
  encodings/fsst/src/compute/compare.rs
Labels: performance

#3344 fix[duckdb]: vortex write nullability from view
  duckdb-vortex/src/vortex_write.cpp
Labels: bug, fix

#3345 Faster list filter
  vortex-array/src/arrays/list/compute/filter.rs
Labels: performance

#3272 Truncate stats on write
  Cargo.lock
  duckdb-vortex/src/include/vortex_common.hpp
  vortex-array/src/builders/decimal.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/serde.rs
  vortex-array/src/stats/array.rs
  vortex-array/src/stats/flatbuffers.rs
  vortex-array/src/stats/mod.rs
  vortex-array/src/stats/precision.rs
  vortex-buffer/src/string.rs
  vortex-file/src/strategy.rs
  vortex-file/src/writer.rs
  vortex-flatbuffers/flatbuffers/vortex-array/array.fbs
  vortex-flatbuffers/src/generated/array.rs
  vortex-flatbuffers/src/generated/message.rs
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/file_stats.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/stats/mod.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/builder.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
  vortex-layout/src/strategy.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/datafusion.rs
  vortex-scalar/src/decimal.rs
  vortex-scalar/src/scalar_value/binary.rs
  vortex-scalar/src/scalar_value/mod.rs
  vortex-scalar/src/scalar_value/utf8.rs
  vortex-scalar/src/utf8.rs
Labels: wire-break

#3293 duckdb: free layout readers after usage
  duckdb-vortex/src/include/vortex_common.hpp
  duckdb-vortex/src/include/vortex_error.hpp
  duckdb-vortex/src/include/vortex_layout_reader.hpp
  duckdb-vortex/src/vortex_scan.cpp
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/array.rs
  vortex-ffi/src/file.rs
Labels: performance

#3351 fix: force set duckdb version
  bench-vortex/src/engines/ddb/mod.rs
Labels: bug, fix

#3352 Return null-d array in `between`
  vortex-array/src/compute/between.rs
  vortex-array/src/compute/compare.rs
  vortex-array/src/test_harness.rs
Labels: bug

#3342 feat[duckdb]: add a decimal test
  duckdb-vortex/test/sql/table.test
  duckdb-vortex/test/sql/table.test_slow
Labels: feature, chore

#3358 feat[ffi]: add a session used for caching
  Cargo.lock
  duckdb-vortex/src/include/vortex_common.hpp
  duckdb-vortex/src/include/vortex_session.hpp
  duckdb-vortex/src/vortex_scan.cpp
  vortex-ffi/Cargo.toml
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/file.rs
  vortex-ffi/src/lib.rs
  vortex-ffi/src/session.rs
Labels: feature

#3362 Idempotent DuckDB bench
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/engines/ddb/mod.rs
Labels: chore

#3363 File pruning when set
  duckdb-vortex/src/include/vortex_common.hpp
  duckdb-vortex/src/include/vortex_layout_reader.hpp
  duckdb-vortex/src/vortex_scan.cpp
  vortex-expr/src/pruning.rs
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/array.rs
  vortex-ffi/src/file.rs
  vortex-file/src/file.rs
  vortex-file/src/lib.rs
  vortex-file/src/pruning.rs
  vortex-layout/src/scan/mod.rs
Labels: feature, performance

#3366 ci: set job timeouts
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/fuzz.yml
  .github/workflows/generate-benchmarks-s3.yml
  .github/workflows/publish.yml
  .github/workflows/sql-benchmarks.yml
  .github/workflows/sql-pr.yml
Labels: chore

#3365 feat: verify duckdb tpch results
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/tpch_results/duckdb/q01.csv
  bench-vortex/tpch_results/duckdb/q02.csv
  bench-vortex/tpch_results/duckdb/q03.csv
  bench-vortex/tpch_results/duckdb/q04.csv
  bench-vortex/tpch_results/duckdb/q05.csv
  bench-vortex/tpch_results/duckdb/q06.csv
  bench-vortex/tpch_results/duckdb/q07.csv
  bench-vortex/tpch_results/duckdb/q08.csv
  bench-vortex/tpch_results/duckdb/q09.csv
  bench-vortex/tpch_results/duckdb/q10.csv
  bench-vortex/tpch_results/duckdb/q11.csv
  bench-vortex/tpch_results/duckdb/q12.csv
  bench-vortex/tpch_results/duckdb/q13.csv
  bench-vortex/tpch_results/duckdb/q14.csv
  bench-vortex/tpch_results/duckdb/q15.csv
  bench-vortex/tpch_results/duckdb/q16.csv
  bench-vortex/tpch_results/duckdb/q17.csv
  bench-vortex/tpch_results/duckdb/q18.csv
  bench-vortex/tpch_results/duckdb/q19.csv
  bench-vortex/tpch_results/duckdb/q20.csv
  bench-vortex/tpch_results/duckdb/q21.csv
  bench-vortex/tpch_results/duckdb/q22.csv
Labels: feature

#3378 FromArrowArray is implemented for &dyn Array instead of ArrayRef
  vortex-array/src/arrays/varbin/canonical.rs
  vortex-array/src/arrow/array.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/arrow/record_batch.rs
  vortex-array/src/compute/boolean.rs
  vortex-array/src/compute/filter.rs
  vortex-array/src/compute/mask.rs
  vortex-array/src/compute/numeric.rs
  vortex-duckdb/src/convert/array/array_ref.rs
  vortex-python/src/arrays/from_arrow.rs
Labels: feature

#3380 fix selection to mask transformation
  vortex-layout/src/scan/selection.rs
Labels: fix

#3383 Disable bench workflow so github cancels stuck run?
  .github/workflows/bench.yml
Labels: bug

#3387 perf: move can prune into ffi method and call it once
  duckdb-vortex/src/include/vortex_common.hpp
  duckdb-vortex/src/vortex_scan.cpp
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/file.rs
Labels: performance

#3391 chore[duckdb]: Update gitignore
  duckdb-vortex/.gitignore
Labels: chore

#3390 set duckdb version
  duckdb-vortex/Makefile
Labels: bug, fix

#3392 Revert 3381 ngates/find latest commit
  .github/workflows/bench-pr.yml
  .github/workflows/sql-benchmarks.yml
  scripts/compare-benchmark-jsons.py
Labels: chore

#3395 ci: only run tpch verification on CI
  bench-vortex/src/bin/tpch.rs
Labels: chore, fix

#3404 fix: handle zero length array encoding
  vortex-file/src/strategy.rs
Labels: bug, fix

#3408 Use mozilla-actions/sccache-action to install sccache for c++ builds
  .github/actions/setup-c++/action.yml
Labels: chore

#3399 perf[duckdb]: push down dynamic filters in scan
  duckdb-vortex/.gitignore
  duckdb-vortex/README.md
  duckdb-vortex/src/include/vortex_expr.hpp
  duckdb-vortex/src/vortex_expr.cpp
  duckdb-vortex/src/vortex_scan.cpp
Labels: performance

#3411 fix[duckdb]: scan local state termination condition update
  duckdb-vortex/src/vortex_scan.cpp
  vortex-layout/src/scan/mod.rs
Labels: fix

#3415 PValue hash follows PartialEq implementation behaviour and upcasts
  vortex-scalar/src/pvalue.rs
Labels: bug

#3416 fix(java): vortex-jni and Java final fixes
  java/vortex-jni/src/main/java/dev/vortex/api/DType.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIDType.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeDTypeMethods.java
  vortex-jni/src/array.rs
  vortex-jni/src/dtype.rs
Labels: fix
