Repository vortex-data/vortex, pull requests merged in 2025-06, with the labels that each got.

#3428 PR labels workflow
  .github/workflows/labels.yml
Labels: chore

#3429 Fix github repository variable
  .github/workflows/labels.yml
Labels: chore

#3425 Vortex FFI Updates
  docs/api/c/arrays.rst
  docs/api/c/dtypes.rst
  docs/api/c/ffi.rst
  docs/api/c/index.rst
  docs/conf.py
  docs/index.md
  duckdb-vortex/src/include/vortex_common.hpp
  duckdb-vortex/src/include/vortex_error.hpp
  duckdb-vortex/src/include/vortex_session.hpp
  duckdb-vortex/src/vortex_scan.cpp
  fuzz/fuzz_targets/file_io.rs
  vortex-array/src/array/convert.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/struct_.rs
  vortex-ffi/README.md
  vortex-ffi/cbindgen.toml
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/array.rs
  vortex-ffi/src/array_iterator.rs
  vortex-ffi/src/dtype.rs
  vortex-ffi/src/dtype_struct.rs
  vortex-ffi/src/duckdb/exporter.rs
  vortex-ffi/src/duckdb/mod.rs
  vortex-ffi/src/error.rs
  vortex-ffi/src/file.rs
  vortex-ffi/src/lib.rs
  vortex-ffi/src/log.rs
  vortex-ffi/src/macros.rs
  vortex-ffi/src/ptype.rs
  vortex-ffi/src/session.rs
  vortex-ffi/src/sink.rs
  vortex-ffi/src/string.rs
  vortex-jni/src/dtype.rs
Labels: feature

#3364 layout writer + strategy refactor for parallel writes
  Cargo.lock
  Cargo.toml
  bench-vortex/src/compress/vortex.rs
  bench-vortex/src/public_bi.rs
  encodings/sequence/Cargo.toml
  encodings/sequence/src/serde.rs
  vortex-array/src/context.rs
  vortex-datafusion/src/persistent/sink.rs
  vortex-file/Cargo.toml
  vortex-file/src/memory.rs
  vortex-file/src/segments/writer.rs
  vortex-file/src/strategy.rs
  vortex-file/src/writer.rs
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/chunked/writer.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/dict/writer/repeating.rs
  vortex-layout/src/layouts/file_stats.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/lib.rs
  vortex-layout/src/scan/executor.rs
  vortex-layout/src/scan/split_by.rs
  vortex-layout/src/segments/sink.rs
  vortex-layout/src/segments/test.rs
  vortex-layout/src/sequence.rs
  vortex-layout/src/strategy.rs
  vortex-layout/src/writer.rs
Labels: performance

#3434 Rename StructDType to StructFields
  docs/api/c/dtypes.rst
  duckdb-vortex/src/vortex_scan.cpp
  fuzz/fuzz_targets/file_io.rs
  fuzz/src/filter.rs
  fuzz/src/slice.rs
  vortex-array/src/arrays/chunked/decode.rs
  vortex-array/src/arrays/struct_/compute/filter.rs
  vortex-array/src/arrays/struct_/compute/mask.rs
  vortex-array/src/arrays/struct_/compute/mod.rs
  vortex-array/src/arrays/struct_/mod.rs
  vortex-array/src/builders/struct_.rs
  vortex-array/src/compute/min_max.rs
  vortex-datafusion/src/memory/provider.rs
  vortex-dtype/src/arbitrary.rs
  vortex-dtype/src/arrow.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/serde/flatbuffers/mod.rs
  vortex-dtype/src/serde/flatbuffers/project.rs
  vortex-dtype/src/serde/proto.rs
  vortex-dtype/src/struct_.rs
  vortex-duckdb/src/convert/types/from.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/literal.rs
  vortex-expr/src/merge.rs
  vortex-expr/src/pack.rs
  vortex-expr/src/transform/field_mask.rs
  vortex-expr/src/transform/immediate_access.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/transform/remove_merge.rs
  vortex-expr/src/transform/remove_select.rs
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/dtype.rs
  vortex-ffi/src/duckdb/mod.rs
  vortex-ffi/src/lib.rs
  vortex-ffi/src/struct_fields.rs
  vortex-file/src/pruning.rs
  vortex-file/src/tests.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
  vortex-python/src/dtype/factory.rs
  vortex-python/src/scalar/factory.rs
  vortex-scalar/src/display.rs
  vortex-scalar/src/proto.rs
  vortex-scalar/src/scalar_value/mod.rs
  vortex-scalar/src/struct_.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: chore

#3435 layout writer tweaks
  vortex-array/src/context.rs
  vortex-file/src/strategy.rs
  vortex-file/src/writer.rs
  vortex-layout/src/layouts/buffered.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/mod.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/scan/executor.rs
  vortex-layout/src/segments/sink.rs
Labels: chore

#3437 fix: add limit clause to tpc-h queries
  .github/workflows/labels.yml
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/tpch/q10.sql
  bench-vortex/tpch/q18.sql
  bench-vortex/tpch/q2.sql
  bench-vortex/tpch/q21.sql
  bench-vortex/tpch/q3.sql
Labels: bug, fix

#3423 fix: Handle comparing VarBinArray to other non VarBin Utf8/BinaryDType arrays
  vortex-array/src/arrays/varbin/compute/compare.rs
Labels: fix

#3410 Adds `list_contains` expression
  vortex-array/src/compute/list.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/list_contains.rs
  vortex-proto/proto/expr.proto
  vortex-proto/src/generated/vortex.expr.rs
Labels: feature

#3445 fix: struct array must skip its validity child
  vortex-array/src/arrays/struct_/serde.rs
  vortex-layout/src/layouts/flat/writer.rs
Labels: fix

#3447 feat[vortex-expr]: let expression
  duckdb-vortex/src/include/vortex_expr.hpp
  duckdb-vortex/src/vortex_expr.cpp
  encodings/sequence/src/serde.rs
  vortex-datafusion/src/convert/exprs.rs
  vortex-datafusion/src/persistent/config.rs
  vortex-datafusion/src/persistent/source.rs
  vortex-expr/src/between.rs
  vortex-expr/src/binary.rs
  vortex-expr/src/cast.rs
  vortex-expr/src/get_item.rs
  vortex-expr/src/identity.rs
  vortex-expr/src/is_null.rs
  vortex-expr/src/let_.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/like.rs
  vortex-expr/src/list_contains.rs
  vortex-expr/src/literal.rs
  vortex-expr/src/merge.rs
  vortex-expr/src/not.rs
  vortex-expr/src/pack.rs
  vortex-expr/src/pruning.rs
  vortex-expr/src/registry.rs
  vortex-expr/src/scope.rs
  vortex-expr/src/select.rs
  vortex-expr/src/transform/field_mask.rs
  vortex-expr/src/transform/immediate_access.rs
  vortex-expr/src/transform/match_between.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/transform/remove_merge.rs
  vortex-expr/src/transform/remove_select.rs
  vortex-expr/src/transform/simplify_typed.rs
  vortex-expr/src/traversal/mod.rs
  vortex-expr/src/var.rs
  vortex-ffi/src/file.rs
  vortex-file/src/tests.rs
  vortex-jni/src/file.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/scan/mod.rs
  vortex-proto/proto/expr.proto
  vortex-proto/src/generated/vortex.expr.rs
  vortex-python/src/dataset.rs
  vortex-python/src/expr/mod.rs
  vortex-python/src/file.rs
  vortex-tui/src/browse/ui/layouts.rs
  vortex/src/lib.rs
Labels: feature

#3444 fix: ddb build
  .gitignore
  Cargo.lock
  Cargo.toml
  vortex-duckdb-ext/build.rs
  vortex-duckdb-ext/cbindgen.toml
  vortex-duckdb-ext/cpp/CMakeLists.txt
  vortex-duckdb-ext/cpp/include/duckdb_vx/data.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/error.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/expr.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/function.h
  vortex-duckdb-ext/include/vortex.h
  vortex-duckdb-ext/src/duckdb/selection_vector.rs
  vortex-duckdb-ext/src/duckdb/vector.rs
  vortex-duckdb-ext/src/exporter/dict.rs
  vortex-duckdb-ext/src/exporter/mod.rs
  vortex-duckdb-ext/src/exporter/run_end.rs
  vortex-duckdb/src/exporter/mod.rs
Labels: bug, fix

#3450 Update bench-vortex readme
  bench-vortex/README.md
Labels: chore

#3455 chore: layout cleanups
  Cargo.toml
  vortex-file/src/file.rs
  vortex-file/src/open.rs
  vortex-layout/src/layout.rs
  vortex-layout/src/layouts/chunked/mod.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/dict/mod.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/flat/mod.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/reader.rs
  vortex-layout/src/scan/split_by.rs
  vortex-layout/src/vtable.rs
  vortex-layout/src/writer.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: chore

#3457 chore: clang-format vortex-duckdb-ext C++ source files
  vortex-duckdb-ext/.clang-format
  vortex-duckdb-ext/build.rs
  vortex-duckdb-ext/cbindgen.toml
  vortex-duckdb-ext/cpp/data.cpp
  vortex-duckdb-ext/cpp/error.cpp
  vortex-duckdb-ext/cpp/expr.cpp
  vortex-duckdb-ext/cpp/include/duckdb_vx/data.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/data.hpp
  vortex-duckdb-ext/cpp/include/duckdb_vx/error.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/expr.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/function.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/scalar_function.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/table_filter.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/table_function.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/vector.h
  vortex-duckdb-ext/cpp/scalar_function.cpp
  vortex-duckdb-ext/cpp/table_filter.cpp
  vortex-duckdb-ext/cpp/table_function.cpp
  vortex-duckdb-ext/cpp/vector.cpp
  vortex-duckdb-ext/include/vortex.h
Labels: chore

#3448 list_contains to use any semantics
  vortex-array/src/arrays/bool/mod.rs
  vortex-array/src/arrays/bool/test.rs
  vortex-array/src/compute/list.rs
  vortex-duckdb-ext/src/cpp.rs
  vortex-expr/src/list_contains.rs
  vortex-expr/src/registry.rs
  vortex-proto/proto/expr.proto
  vortex-proto/src/generated/vortex.expr.rs
Labels: fix

#3462 fix: decimal casting
  vortex-array/src/arrays/decimal/compute/between.rs
  vortex-datafusion/src/persistent/metrics.rs
  vortex-duckdb-ext/src/cpp.rs
  vortex-scalar/src/decimal.rs
Labels: fix

#3464 ci: fix JAR packaging
  .github/workflows/publish.yml
Labels: fix

#3465 chore: split pruning.rs into four files.
  vortex-expr/src/pruning.rs
  vortex-expr/src/pruning/field_or_identity.rs
  vortex-expr/src/pruning/mod.rs
  vortex-expr/src/pruning/pruning_predicate.rs
  vortex-expr/src/pruning/pruning_predicate_rewriter.rs
  vortex-expr/src/pruning/relation.rs
  vortex-layout/src/layouts/zoned/reader.rs
Labels: chore

#3470 fix: remove `cpp.rs` from version control
  vortex-duckdb-ext/.gitignore
  vortex-duckdb-ext/src/cpp.rs
  vortex-duckdb-ext/src/lib.rs
Labels: fix

#3472 chore: clarify duckdb ext ownership API fn names
  vortex-duckdb-ext/cpp/vector.cpp
  vortex-duckdb-ext/src/duckdb/connection.rs
  vortex-duckdb-ext/src/duckdb/data.rs
  vortex-duckdb-ext/src/duckdb/data_chunk.rs
  vortex-duckdb-ext/src/duckdb/database.rs
  vortex-duckdb-ext/src/duckdb/expr.rs
  vortex-duckdb-ext/src/duckdb/logical_type.rs
  vortex-duckdb-ext/src/duckdb/mod.rs
  vortex-duckdb-ext/src/duckdb/scalar_function.rs
  vortex-duckdb-ext/src/duckdb/selection_vector.rs
  vortex-duckdb-ext/src/duckdb/table_filter.rs
  vortex-duckdb-ext/src/duckdb/table_function/bind.rs
  vortex-duckdb-ext/src/duckdb/table_function/init.rs
  vortex-duckdb-ext/src/duckdb/table_function/mod.rs
  vortex-duckdb-ext/src/duckdb/table_function/pushdown_complex_filter.rs
  vortex-duckdb-ext/src/duckdb/value.rs
  vortex-duckdb-ext/src/duckdb/vector.rs
  vortex-duckdb-ext/src/lib.rs
Labels: chore

#3461 feat: list_contains constant list, array value
  vortex-array/src/arrays/bool/test.rs
  vortex-array/src/compute/list.rs
  vortex-expr/src/list_contains.rs
Labels: feature

#3482 chore: Fix comments that could be rustdoc
  bench-vortex/src/tpch/dbgen.rs
  bench-vortex/src/tpch/mod.rs
  encodings/alp/src/alp/compute/compare.rs
  encodings/fastlanes/src/bitpacking/compute/take.rs
  encodings/fsst/benches/fsst_compress.rs
  encodings/fsst/src/tests.rs
  encodings/sequence/src/array.rs
  vortex-array/src/arrays/chunked/compute/filter.rs
  vortex-array/src/arrays/primitive/compute/is_constant.rs
  vortex-array/src/arrays/varbinview/mod.rs
  vortex-array/src/builders/decimal.rs
  vortex-array/src/canonical.rs
  vortex-array/src/compute/list.rs
  vortex-array/src/stats/bound.rs
  vortex-array/src/stats/stats_set.rs
  vortex-btrblocks/src/lib.rs
  vortex-buffer/benches/vortex_buffer.rs
  vortex-buffer/src/spec_extend.rs
  vortex-duckdb/src/convert/array/cache.rs
  vortex-duckdb/src/convert/types/from.rs
  vortex-expr/src/analysis.rs
  vortex-file/src/file.rs
  vortex-python/src/scalar/factory.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: chore

#3489 chore: cleanup scan task execution to be clearer
  vortex-expr/src/transform/immediate_access.rs
  vortex-layout/src/scan/mod.rs
  vortex-layout/src/scan/selection.rs
  vortex-layout/src/scan/tasks.rs
Labels: chore

#3493 chore: rename vortex-common -> vortex-utils so we can publish
  Cargo.lock
  Cargo.toml
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/display.rs
  bench-vortex/src/metrics.rs
  bench-vortex/src/public_bi.rs
  bench-vortex/src/random_access/take.rs
  bench-vortex/src/tpch/mod.rs
  encodings/alp/Cargo.toml
  encodings/alp/src/alp_rd/mod.rs
  encodings/dict/Cargo.toml
  encodings/dict/src/builders/bytes.rs
  encodings/dict/src/builders/primitive.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/array_ops.rs
  fuzz/fuzz_targets/file_io.rs
  fuzz/src/lib.rs
  vortex-array/Cargo.toml
  vortex-array/src/arrays/primitive/top_value.rs
  vortex-array/src/context.rs
  vortex-array/src/patches.rs
  vortex-btrblocks/Cargo.toml
  vortex-btrblocks/benches/compress.rs
  vortex-btrblocks/src/float/dictionary.rs
  vortex-btrblocks/src/float/stats.rs
  vortex-btrblocks/src/integer.rs
  vortex-btrblocks/src/integer/dictionary.rs
  vortex-btrblocks/src/integer/stats.rs
  vortex-btrblocks/src/string.rs
  vortex-datafusion/src/persistent/cache.rs
  vortex-duckdb-ext/src/exporter/cache.rs
  vortex-duckdb/src/convert/array/cache.rs
  vortex-expr/Cargo.toml
  vortex-expr/src/lib.rs
  vortex-expr/src/pruning/pruning_predicate.rs
  vortex-expr/src/pruning/relation.rs
  vortex-expr/src/registry.rs
  vortex-expr/src/scope.rs
  vortex-expr/src/transform/field_mask.rs
  vortex-expr/src/transform/immediate_access.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/traversal/mod.rs
  vortex-expr/src/traversal/references.rs
  vortex-ffi/src/session.rs
  vortex-file/Cargo.toml
  vortex-file/src/driver.rs
  vortex-jni/src/file.rs
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/sequence.rs
  vortex-tui/src/browse/ui/segments.rs
  vortex-utils/Cargo.toml
  vortex-utils/src/aliases/hash_map.rs
  vortex-utils/src/aliases/hash_set.rs
  vortex-utils/src/aliases/mod.rs
  vortex-utils/src/lib.rs
  vortex/Cargo.toml
  vortex/src/lib.rs
Labels: chore

#3491 feat: FieldPath::resolve, ::exists, and AccesPath::new
  vortex-dtype/src/field.rs
  vortex-expr/src/lib.rs
Labels: feature

#3497 fix[vortex-array]: list_contains compare opposed nullable list values or search values
  vortex-array/src/compute/list.rs
Labels: fix

#3494 feat: link extension against prebuilt duckdb lib
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  vortex-duckdb-ext/Cargo.toml
  vortex-duckdb-ext/build.rs
  vortex-duckdb-ext/src/lib.rs
Labels: feature, chore

#3504 fix: Arrow timestamps are in an _unknown_ timezone
  vortex-dtype/src/datetime/temporal.rs
  vortex-scalar/src/display.rs
Labels: fix

#3509 fix: deserialize ident proto expressions as the new Var("")
  vortex-expr/src/registry.rs
  vortex-expr/src/var.rs
Labels: fix

#3510 feat: use tree display for df emit plan
  bench-vortex/src/engines/df/mod.rs
Labels: feature

#3515 feat: scope dynamic symbol resolution to `vortex-python`
  .cargo/config.toml
  vortex-duckdb-ext/build.rs
  vortex-python/.cargo/config.toml
Labels: feature

#3500 stats calculation parallelism in layout writer
  vortex-file/src/strategy.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/writer.rs
Labels: performance

#3483 feat: Initial limit pushdown in the scan
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/clickbench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/engines/df/mod.rs
  bench-vortex/src/public_bi.rs
  vortex-datafusion/examples/vortex_table.rs
  vortex-datafusion/src/lib.rs
  vortex-datafusion/src/persistent/format.rs
  vortex-datafusion/src/persistent/mod.rs
  vortex-datafusion/src/persistent/opener.rs
  vortex-datafusion/src/persistent/source.rs
  vortex-dtype/src/field_mask.rs
  vortex-layout/src/scan/mod.rs
  vortex-layout/src/scan/tasks.rs
  vortex-mask/src/lib.rs
Labels: feature

#3517 duckdb: temporal, list & decimal dtype conversions
  vortex-duckdb-ext/src/convert/dtype.rs
  vortex-duckdb-ext/src/scan.rs
Labels: feature

#3524 feat: do not swallow errors from streams being written
  vortex-layout/src/layouts/dict/writer/mod.rs
Labels: feature

#3532 duckdb: file list via glob
  Cargo.lock
  Cargo.toml
  duckdb-vortex/src/vortex_scan.cpp
  vortex-duckdb-ext/Cargo.toml
  vortex-duckdb-ext/src/lib.rs
  vortex-duckdb-ext/src/scan.rs
Labels: chore

#3525 Pco encoding
  Cargo.lock
  Cargo.toml
  encodings/pco/Cargo.toml
  encodings/pco/src/array.rs
  encodings/pco/src/lib.rs
  encodings/pco/src/serde.rs
  encodings/pco/src/test.rs
  vortex-array/src/vtable/validity.rs
  vortex/Cargo.toml
  vortex/src/lib.rs
  vortex/src/session.rs
Labels: feature

#3537 Zstd encoding improvements
  Cargo.lock
  encodings/zstd/Cargo.toml
  encodings/zstd/src/array.rs
  encodings/zstd/src/serde.rs
  encodings/zstd/src/test.rs
Labels: chore

#3534 feat[vortex-duckdb-ext]: scan with table filter
  vortex-duckdb-ext/cpp/expr.cpp
  vortex-duckdb-ext/cpp/include/duckdb_vx/table_filter.h
  vortex-duckdb-ext/cpp/table_filter.cpp
  vortex-duckdb-ext/src/convert/dtype.rs
  vortex-duckdb-ext/src/convert/expr.rs
  vortex-duckdb-ext/src/convert/mod.rs
  vortex-duckdb-ext/src/convert/scalar.rs
  vortex-duckdb-ext/src/duckdb/table_filter.rs
  vortex-duckdb-ext/src/duckdb/value.rs
  vortex-duckdb-ext/src/scan.rs
  vortex-expr/src/binary.rs
Labels: feature

#3535 fix: teach dict layout how to evaluate expressions with non-trivial nullability
  Cargo.lock
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/dict/reader.rs
Labels: bug, fix

#3541 duckdb: impl clone for bind data
  vortex-duckdb-ext/cpp/include/duckdb_vx/logical_type.h
  vortex-duckdb-ext/cpp/include/duckdb_vx/table_function.h
  vortex-duckdb-ext/cpp/logical_type.cpp
  vortex-duckdb-ext/cpp/table_function.cpp
  vortex-duckdb-ext/src/duckdb/logical_type.rs
  vortex-duckdb-ext/src/duckdb/table_function/bind.rs
  vortex-duckdb-ext/src/duckdb/table_function/mod.rs
  vortex-duckdb-ext/src/scan.rs
Labels: chore

#3552 chore: fix table comment to be real markdown
  java/testfiles/src/main.rs
Labels: chore, fix

#3557 duckdb: factor out fns from `init_global`
  vortex-duckdb-ext/src/scan.rs
Labels: chore

#3530 chore: StructFields field access returns option instead of result
  vortex-array/src/compute/min_max.rs
  vortex-datafusion/src/persistent/format.rs
  vortex-dtype/src/field.rs
  vortex-dtype/src/struct_.rs
  vortex-expr/src/get_item.rs
  vortex-expr/src/scope.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/transform/remove_merge.rs
  vortex-file/src/pruning.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-python/src/scalar/struct_.rs
  vortex-scalar/src/struct_.rs
Labels: chore

#3565 chore: Add Field::as_name and remove unused From impls
  vortex-dtype/src/field.rs
  vortex-expr/src/pruning/pruning_expr.rs
Labels: chore

#3560 datafusion 48
  Cargo.lock
  Cargo.toml
  bench-vortex/src/clickbench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/public_bi.rs
  vortex-datafusion/examples/vortex_table.rs
  vortex-datafusion/src/lib.rs
  vortex-datafusion/src/persistent/format.rs
  vortex-datafusion/src/persistent/mod.rs
  vortex-datafusion/src/persistent/sink.rs
  vortex-datafusion/src/persistent/source.rs
Labels: chore

#3568 chore: Add IntoArray for TemporalArray
  vortex-array/src/arrays/datetime/mod.rs
Labels: chore

#3566 Chore: Implement std::io::Write for ByteBufferMut
  encodings/pco/src/array.rs
  vortex-buffer/src/buffer_mut.rs
Labels: chore

#3572 docs: fix DType docs
  docs/concepts/dtypes.md
Labels: documentation, fix

#3577 bug[decimal]: to arrow use precision not scale to decide arrow type
  vortex-dtype/src/arrow.rs
Labels: bug

#3584 chore: add `StructFields::merge`
  vortex-dtype/src/struct_.rs
Labels: chore

#3582 chore[fuzzer]: nullable take indices and compare scalar
  fuzz/src/filter.rs
  fuzz/src/lib.rs
  fuzz/src/sort.rs
  fuzz/src/take.rs
Labels: chore

#3581 chore[fuzzer]: update readme
  fuzz/README.md
Labels: chore

#3592 chore: simplify rpath handling
  .cargo/config.toml
  .github/workflows/bench-pr.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/build.rs
  vortex-duckdb-ext/build.rs
Labels: chore

#3583 chore[fuzzer]: add array casting op
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.toml
  fuzz/fuzz_targets/array_ops.rs
  fuzz/src/cast.rs
  fuzz/src/lib.rs
  vortex-array/src/compute/cast.rs
Labels: chore

#3588 feat[vortex-duckdb-ext]: add vx duckdb type conversion
  vortex-duckdb-ext/src/convert/dtype.rs
  vortex-duckdb-ext/src/convert/scalar.rs
Labels: feature

#3595 chore[fuzzer]: move array and file ops into their own modules
  fuzz/src/array/cast.rs
  fuzz/src/array/compare.rs
  fuzz/src/array/filter.rs
  fuzz/src/array/mod.rs
  fuzz/src/array/search_sorted.rs
  fuzz/src/array/slice.rs
  fuzz/src/array/sort.rs
  fuzz/src/array/take.rs
  fuzz/src/file/mod.rs
  fuzz/src/lib.rs
Labels: chore

#3593 duckdb: marshal query results via C API
  Cargo.lock
  bench-vortex/src/engines/ddb2/mod.rs
  vortex-duckdb-ext/Cargo.toml
  vortex-duckdb-ext/src/duckdb/connection.rs
  vortex-duckdb-ext/src/duckdb/mod.rs
  vortex-duckdb-ext/src/duckdb/query_result.rs
  vortex-duckdb-ext/src/lib.rs
  vortex-duckdb-ext/src/scan_tests.rs
  vortex-duckdb-ext/src/vortex_scan_tests.rs
Labels: chore

#3606 bug[vortex-duckdb-ext]: fix the scan termination condition
  vortex-duckdb-ext/src/duckdb/data_chunk.rs
  vortex-duckdb-ext/src/duckdb/query_result.rs
  vortex-duckdb-ext/src/scan.rs
Labels: fix

#3602 chore: kill duckdb ci build tasks
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/tpch/duckdb.rs
  vortex-duckdb-ext/build.rs
Labels: chore

#3614 fix: drop ddb skip build flag
  .github/workflows/sql-benchmarks.yml
Labels: bug, fix

#3620 Fix: Handle DateTimeParts compare with nullable rhs and non nullable lhs
  encodings/datetime-parts/src/compress.rs
  encodings/datetime-parts/src/compute/compare.rs
  vortex-array/src/compute/compare.rs
Labels: fix

#3627 fix: duckdb vx ext memory leak
  vortex-duckdb/cpp/table_function.cpp
Labels: fix

#3631 fix: duckdb `varchar` leak
  vortex-duckdb/src/convert/expr.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/duckdb/value.rs
  vortex-duckdb/src/scan.rs
Labels: fix

#3630 fix: `duckdb_logical_type` leak
  vortex-duckdb/src/duckdb/vector.rs
Labels: fix

#3638 Fix: delay getting benchmarks s3 token until after binary has been built
  .github/workflows/generate-benchmarks-s3.yml
  .github/workflows/sql-benchmarks.yml
Labels: chore

#3628 bug[vortex-array]: take compare nullable bugs
  encodings/dict/src/compute/mod.rs
  encodings/fsst/src/compute/mod.rs
  vortex-array/src/arrays/varbin/compute/compare.rs
  vortex-array/src/compute/mod.rs
Labels: fix

#3636 chore: move ci to duckdb v1.3.1
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/tpch/results/duckdb/q02.csv
  bench-vortex/tpch/results/duckdb/q10.csv
  bench-vortex/tpch/results/duckdb/q15.csv
  bench-vortex/tpch/results/duckdb/q16.csv
  bench-vortex/tpch/results/duckdb/q18.csv
  bench-vortex/tpch/results/duckdb/q20.csv
  bench-vortex/tpch/results/duckdb/q21.csv
Labels: fix

#3642 chore: Do we need gzip install?
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
Labels: chore

#3637 list is_constant
  vortex-array/src/arrays/list/compute/is_constant.rs
  vortex-array/src/arrays/list/compute/mod.rs
  vortex-array/src/compute/is_constant.rs
Labels: fix

#3648 fix: `TableFunction` leak
  vortex-duckdb/cpp/table_function.cpp
Labels: fix

#3508 docs: more docs around AnalysisExpr and boolean operators
  vortex-array/src/compute/boolean.rs
  vortex-expr/src/analysis.rs
  vortex-expr/src/exprs/operators.rs
  vortex-layout/src/layouts/zoned/reader.rs
Labels: chore

#3650 fix[encodings]: decimal-byte-parts-array compare when scalar is larger than any value in the array
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/compare.rs
Labels: fix

#3665 feat: multiversion for primitive take
  Cargo.lock
  Cargo.toml
  vortex-array/Cargo.toml
  vortex-array/src/arrays/primitive/compute/take.rs
Labels: feature

#3661 Run clickbench file download on a local rayon pool
  bench-vortex/src/clickbench.rs
Labels: chore

#3667 chore: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#3668 chore: coveralls ignore generated/language-binding code
  .github/workflows/ci.yml
Labels: chore

#3672 Add scope variables to expression scope
  vortex-expr/src/lib.rs
  vortex-expr/src/scope.rs
  vortex-expr/src/scope_vars.rs
Labels: feature

#3676 chore: drop obsolete `vortex-duckdb_v1` crate
  vortex-duckdb_v1/Cargo.toml
  vortex-duckdb_v1/cbindgen.toml
  vortex-duckdb_v1/src/buffer/mod.rs
  vortex-duckdb_v1/src/convert/array/array_ref.rs
  vortex-duckdb_v1/src/convert/array/cache.rs
  vortex-duckdb_v1/src/convert/array/data_chunk_adaptor.rs
  vortex-duckdb_v1/src/convert/array/decimal.rs
  vortex-duckdb_v1/src/convert/array/mod.rs
  vortex-duckdb_v1/src/convert/array/table.rs
  vortex-duckdb_v1/src/convert/mod.rs
  vortex-duckdb_v1/src/convert/scalar/mod.rs
  vortex-duckdb_v1/src/convert/types/from.rs
  vortex-duckdb_v1/src/convert/types/mod.rs
  vortex-duckdb_v1/src/convert/types/to.rs
  vortex-duckdb_v1/src/exporter/constant.rs
  vortex-duckdb_v1/src/exporter/decimal.rs
  vortex-duckdb_v1/src/exporter/dict.rs
  vortex-duckdb_v1/src/exporter/mod.rs
  vortex-duckdb_v1/src/exporter/primitive.rs
  vortex-duckdb_v1/src/exporter/run_end.rs
  vortex-duckdb_v1/src/exporter/varbinview.rs
  vortex-duckdb_v1/src/lib.rs
Labels: chore

#3605 feat: teach ScanBuilder with_row_index
  vortex-layout/src/layout.rs
  vortex-layout/src/layouts/chunked/mod.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/dict/mod.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/filter.rs
  vortex-layout/src/layouts/flat/mod.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/row_id.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/reader.rs
  vortex-layout/src/scan/mod.rs
  vortex-layout/src/vtable.rs
Labels: feature
