Repository vortex-data/vortex, pull requests merged in 2025-07, with the labels that each got.

#3688 Use config:recommended instead of config:base
  renovate.json
Labels: chore

#3697 fix: Bump polars dependency and fix expr conversion
  uv.lock
  vortex-python/pyproject.toml
  vortex-python/python/vortex/polars_.py
Labels: fix

#3700 fix: skip tpch q6 for duckdb:vortex
  bench-vortex/src/bin/tpch.rs
Labels: fix

#3677 fix: SparseArray handles take with null indices if the fill value is not null
  encodings/sparse/src/compute/take.rs
  vortex-array/benches/take_patches.rs
  vortex-array/src/patches.rs
Labels: fix

#3707 chore: Make sure that workspace is clean after build
  .github/workflows/ci.yml
Labels: chore

#3708 chore: rename error => error_out
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/array.rs
  vortex-ffi/src/array_iterator.rs
  vortex-ffi/src/file.rs
  vortex-ffi/src/sink.rs
Labels: chore

#3721 chore: remove unused `worker` dep from repo
  Cargo.lock
  Cargo.toml
  vortex-error/Cargo.toml
  vortex-error/src/lib.rs
Labels: chore, break

#3726 fix: fix decimal byte parts compare & duckdb as_decimal
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/compare.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/duckdb/value.rs
  vortex-expr/src/pruning/pruning_expr.rs
Labels: fix

#3729 fix: column type leak
  vortex-duckdb/src/duckdb/vector.rs
Labels: fix

#3693 feat[vortex-duckdb]: add copy from function bindings and vortex impl
  Cargo.lock
  vortex-duckdb/Cargo.toml
  vortex-duckdb/build.rs
  vortex-duckdb/cpp/copy_function.cpp
  vortex-duckdb/cpp/include/duckdb_vx.h
  vortex-duckdb/cpp/include/duckdb_vx/copy_function.h
  vortex-duckdb/cpp/include/duckdb_vx/vector.h
  vortex-duckdb/cpp/table_function.cpp
  vortex-duckdb/cpp/vector.cpp
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/mod.rs
  vortex-duckdb/src/convert/vector.rs
  vortex-duckdb/src/copy.rs
  vortex-duckdb/src/duckdb/copy_function/callback.rs
  vortex-duckdb/src/duckdb/copy_function/mod.rs
  vortex-duckdb/src/duckdb/data_chunk.rs
  vortex-duckdb/src/duckdb/mod.rs
  vortex-duckdb/src/duckdb/table_function/bind.rs
  vortex-duckdb/src/duckdb/table_function/init.rs
  vortex-duckdb/src/duckdb/table_function/pushdown_complex_filter.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/exporter/bool.rs
  vortex-duckdb/src/exporter/sequence.rs
  vortex-duckdb/src/exporter/temporal.rs
  vortex-duckdb/src/lib.rs
  vortex-duckdb/src/vortex_e2e_tests.rs
Labels: feature

#3743 fix: teach StructFieldExpressionSplitter the scope of its root expr
  vortex-expr/src/transform/partition.rs
Labels: fix

#3741 chore: run `duckdb:vortex` on clickbench
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/engines/mod.rs
  vortex-duckdb/src/duckdb/database.rs
Labels: chore

#3739 chore[benchmark]: add -o option to specify where the write results
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/compress.rs
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/bin/random_access.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/display.rs
Labels: chore

#3747 feat: Hide as many of FieldNames' Arcs as possible
  bench-vortex/src/datasets/struct_list_of_ints.rs
  encodings/sparse/src/canonical.rs
  java/testfiles/src/main.rs
  vortex-array/src/arrays/chunked/compute/take.rs
  vortex-array/src/arrays/list/compute/is_constant.rs
  vortex-array/src/arrays/struct_/compute/mod.rs
  vortex-array/src/arrays/struct_/mod.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/arrow/record_batch.rs
  vortex-array/src/compute/min_max.rs
  vortex-datafusion/examples/vortex_table.rs
  vortex-datafusion/src/persistent/mod.rs
  vortex-dtype/src/arbitrary.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/field.rs
  vortex-dtype/src/serde/flatbuffers/mod.rs
  vortex-dtype/src/serde/proto.rs
  vortex-dtype/src/struct_.rs
  vortex-duckdb/src/convert/dtype.rs
  vortex-expr/src/arbitrary.rs
  vortex-expr/src/exprs/list_contains.rs
  vortex-expr/src/exprs/literal.rs
  vortex-expr/src/exprs/merge.rs
  vortex-expr/src/exprs/pack.rs
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/transform/field_mask.rs
  vortex-expr/src/transform/remove_select.rs
  vortex-file/src/pruning.rs
  vortex-file/src/tests.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-python/src/dataset.rs
  vortex-scalar/src/display.rs
  vortex-scalar/src/scalar_value/mod.rs
Labels: feature

#3746 chore[benchmark]: support scale factors other than 1 in tpch
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/clickbench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/display.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/measurements.rs
  bench-vortex/src/tpch/duckdb.rs
  bench-vortex/src/tpch/mod.rs
Labels: chore

#3751 chore[benchmark]: add scale factor 100
  .github/workflows/nightly-bench.yml
  .github/workflows/sql-benchmarks.yml
  benchmarks-website/code.js
  benchmarks-website/index.html
Labels: chore

#3752 fix: Make all JNI types support idempotent close
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIArray.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIArrayIterator.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIDType.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIFile.java
Labels: fix

#3755 chore[benchmark]: attach env triple to benchmarks measurements
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/measurements.rs
Labels: chore

#3761 chore: Update OpenSSF badge
  README.md
Labels: chore

#3767 chore: Tell fuzzer to use all cores on the machine
  .github/workflows/fuzz.yml
Labels: chore

#3750 chore: `TakeKernel` for `List`
  vortex-array/src/arrays/list/compute/mod.rs
  vortex-array/src/arrays/list/compute/take.rs
Labels: chore

#3784 chore[bench]: store all run time measurements
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/engines/mod.rs
  bench-vortex/src/measurements.rs
Labels: chore

#3786 ci: Fuzz failures should fail whole job
  .github/workflows/fuzz.yml
Labels: chore

#3789 fix: DecimalByteParts compare with overflow and nullable elements
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/compare.rs
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/filter.rs
  encodings/decimal-byte-parts/src/decimal_byte_parts/mod.rs
  encodings/decimal-byte-parts/src/decimal_byte_parts/serde.rs
  fuzz/fuzz_targets/array_ops.rs
  vortex-array/src/arrays/decimal/compute/take.rs
  vortex-btrblocks/src/decimal.rs
Labels: fix

#3795 Add expression transformation to replace all occurrences of a node
  vortex-expr/src/exprs/pack.rs
  vortex-expr/src/transform/mod.rs
  vortex-expr/src/transform/replace.rs
Labels: feature

#3798 chore: Remove clear-caches action
  .github/workflows/clear-caches.yml
Labels: chore

#3785 chore[bench-vortex]: unify the different benchmark binaries
  .github/workflows/generate-benchmarks-s3.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/README.md
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/benchmark_trait.rs
  bench-vortex/src/bin/clickbench.rs
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/bin/tpch.rs
  bench-vortex/src/clickbench.rs
  bench-vortex/src/clickbench_benchmark.rs
  bench-vortex/src/conversions.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/query_bench.rs
  bench-vortex/src/tpcds/mod.rs
  bench-vortex/src/tpch/execute.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/src/tpch_benchmark.rs
  bench-vortex/src/utils/constants.rs
  bench-vortex/src/utils/file_utils.rs
Labels: chore

#3801 ci: run Rust tests with ASAN
  .github/workflows/ci.yml
  vortex-array/src/arrays/primitive/compute/take/avx2.rs
  vortex-duckdb/src/duckdb/data_chunk.rs
  vortex-duckdb/src/duckdb/logical_type.rs
  vortex-duckdb/src/exporter/bool.rs
  vortex-duckdb/src/exporter/sequence.rs
Labels: chore

#3806 chore[bench]: nightly run sf10
  .github/workflows/nightly-bench.yml
  benchmarks-website/code.js
  benchmarks-website/index.html
Labels: chore

#3807 chore[bench]: parallel file gen
  bench-vortex/src/tpch/tpchgen.rs
Labels: chore

#3803 Generalize expression partition to annotationed expressions
  vortex-expr/src/transform/access_analysis.rs
  vortex-expr/src/transform/annotations.rs
  vortex-expr/src/transform/immediate_access.rs
  vortex-expr/src/transform/mod.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/transform/replace.rs
  vortex-expr/src/transform/var_partition.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/scan/mod.rs
Labels: chore

#3812 fix: Add test for using correct self._dataset variable for scanner schema
  vortex-python/python/vortex/dataset.py
  vortex-python/test/test_dataset.py
Labels: fix

#3817 Add precondition for VortexExpr::replace_children
  vortex-expr/src/exprs/between.rs
  vortex-expr/src/exprs/binary.rs
  vortex-expr/src/exprs/cast.rs
  vortex-expr/src/exprs/get_item.rs
  vortex-expr/src/exprs/is_null.rs
  vortex-expr/src/exprs/like.rs
  vortex-expr/src/exprs/list_contains.rs
  vortex-expr/src/exprs/literal.rs
  vortex-expr/src/exprs/merge.rs
  vortex-expr/src/exprs/not.rs
  vortex-expr/src/exprs/pack.rs
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/exprs/var.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/vtable.rs
Labels: chore

#3818 chore: add sf 0.01 & 0.1 and use 0.01 in ci
  .github/workflows/ci.yml
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/tpch_benchmark.rs
Labels: chore

#3819 Row idx layout reader
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/file.rs
  vortex-file/src/file.rs
  vortex-layout/src/layouts/filter.rs
  vortex-layout/src/layouts/mod.rs
  vortex-layout/src/layouts/partitioned.rs
  vortex-layout/src/layouts/row_id.rs
  vortex-layout/src/layouts/row_idx/expr.rs
  vortex-layout/src/layouts/row_idx/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/reader.rs
  vortex-layout/src/scan/mod.rs
Labels: feature

#3823 Fix empty take for `ChunkedArray`
  vortex-array/src/arrays/chunked/compute/take.rs
  vortex-array/src/compute/take.rs
Labels: fix

#3826 chore: sanitize cxx build flags for vortex-duckdb
  vortex-duckdb/cpp/CMakeLists.txt
Labels: chore

#3824 chore[bench]: generate partitioned tpch files
  Cargo.lock
  bench-vortex/Cargo.toml
  bench-vortex/src/clickbench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/tpcds/mod.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/src/tpch/tpchgen.rs
  bench-vortex/src/tpch_benchmark.rs
Labels: chore

#3830 fix[bench]: nightly config that doesn't fail
  .github/workflows/nightly-bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/tpch/tpchgen.rs
Labels: fix

#3825 feat: Add optimize ArrayOp with VBView implementation
  vortex-array/src/array/mod.rs
  vortex-array/src/arrays/varbinview/ops.rs
  vortex-array/src/builders/varbinview.rs
  vortex-array/src/vtable/operations.rs
Labels: feature

#3835 chore: bump duckdb binaries to 1.3.2
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
Labels: chore

#3837 fix[bench]: correct s3 path to run benchmarks
  .github/workflows/nightly-bench.yml
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/tpch_benchmark.rs
Labels: fix

#3838 fix[bench]: website render data with scale factor as string
  benchmarks-website/code.js
Labels: fix

#3839 chore[ci]: remove clean up from CI
  .github/actions/cleanup/action.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
Labels: chore

#3840 chore[ci]: add duckdb:duckdb to sf=10 run and sf=1000 run
  .github/workflows/nightly-bench.yml
Labels: chore

#3842 chore[fuzz]: smaller machine to save run cost `m8g.2xlarge`
  .github/workflows/fuzz.yml
Labels: chore

#3662 feat: teach SparseArray to canonicalize Null & Decimal
  encodings/sparse/src/canonical.rs
  vortex-array/src/arrays/decimal/mod.rs
  vortex-array/src/arrays/decimal/patch.rs
  vortex-scalar/src/decimal.rs
Labels: feature

#3849 fix[bench-website]: allow sf1000 and missing results
  benchmarks-website/code.js
  benchmarks-website/index.html
Labels: fix

#3850 chore: pull struct case of sparse to_canonical into function
  encodings/sparse/src/canonical.rs
Labels: chore

#3846 fix: teach SparseArray to account for null values when the fill is null
  Cargo.lock
  encodings/sparse/Cargo.toml
  encodings/sparse/src/lib.rs
Labels: fix

#3843 chore: better naming for SendableLayoutFuture
  vortex-layout/src/layouts/buffered.rs
  vortex-layout/src/layouts/chunked/writer.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/strategy.rs
  vortex-layout/src/writer.rs
Labels: chore

#3854 Move array context inside FlatLayout
  vortex-file/src/file.rs
  vortex-file/src/footer/mod.rs
  vortex-layout/src/children.rs
  vortex-layout/src/encoding.rs
  vortex-layout/src/flatbuffers.rs
  vortex-layout/src/layout.rs
  vortex-layout/src/layouts/chunked/mod.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/dict/mod.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/flat/mod.rs
  vortex-layout/src/layouts/flat/reader.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/row_idx/mod.rs
  vortex-layout/src/layouts/struct_/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/reader.rs
  vortex-layout/src/scan/split_by.rs
  vortex-layout/src/vtable.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: chore

#3847 chore: Add `new_expr` to all built-in expressions in the name of consistency
  vortex-dtype/src/field.rs
  vortex-dtype/src/field_mask.rs
  vortex-expr/src/exprs/cast.rs
  vortex-expr/src/exprs/get_item.rs
  vortex-expr/src/exprs/is_null.rs
  vortex-expr/src/exprs/list_contains.rs
  vortex-expr/src/exprs/merge.rs
  vortex-expr/src/exprs/pack.rs
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/pruning/pruning_expr.rs
  vortex-file/src/pruning.rs
Labels: break

#3844 feat[compressor]: wire up sequence array into the compressor
  Cargo.lock
  bench-vortex/src/tpch/tpchgen.rs
  docs/quickstart/python.rst
  encodings/sequence/src/array.rs
  encodings/sequence/src/compress.rs
  encodings/sequence/src/compute/compare.rs
  encodings/sequence/src/compute/list_contains.rs
  encodings/sequence/src/lib.rs
  encodings/sequence/src/serde.rs
  vortex-btrblocks/Cargo.toml
  vortex-btrblocks/src/integer.rs
  vortex-duckdb/src/exporter/sequence.rs
  vortex-layout/src/layouts/row_idx/mod.rs
  vortex-python/src/arrays/compressed.rs
  vortex-python/src/arrays/native.rs
  vortex-python/src/compress.rs
Labels: feature

#3851 feat: Minimal support for extension array casting
  encodings/datetime-parts/src/compute/cast.rs
  vortex-array/src/arrays/bool/compute/cast.rs
  vortex-array/src/arrays/chunked/compute/cast.rs
  vortex-array/src/arrays/constant/compute/cast.rs
  vortex-array/src/arrays/extension/compute/cast.rs
  vortex-array/src/arrays/extension/compute/mod.rs
  vortex-array/src/arrays/list/compute/cast.rs
  vortex-array/src/arrays/primitive/compute/cast.rs
  vortex-array/src/arrays/struct_/compute/cast.rs
  vortex-array/src/arrays/varbin/compute/cast.rs
  vortex-array/src/arrays/varbinview/compute/cast.rs
  vortex-array/src/compute/cast.rs
Labels: feature

#3861 feat[bench]: inter-query memory tracking
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/measurements.rs
  bench-vortex/src/memory.rs
  bench-vortex/src/query_bench.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/src/tpch_benchmark.rs
Labels: feature

#3864 chore: Replace dependency on top level arrow create with individual modules now that pyarrow is a standalone crate
  Cargo.lock
  Cargo.toml
  vortex-duckdb/Cargo.toml
  vortex-duckdb/src/convert/vector.rs
  vortex-jni/Cargo.toml
  vortex-jni/src/array.rs
  vortex-python/Cargo.toml
  vortex-python/src/arrays/from_arrow.rs
  vortex-python/src/arrays/mod.rs
  vortex-python/src/dataset.rs
  vortex-python/src/dtype/mod.rs
  vortex-python/src/file.rs
  vortex-python/src/iter/mod.rs
  vortex-python/src/record_batch_reader.rs
  vortex/Cargo.toml
  vortex/src/lib.rs
Labels: chore

#3866 feat: display
  encodings/dict/src/display.rs
  encodings/dict/src/lib.rs
  vortex-array/src/array/display/mod.rs
  vortex-array/src/array/display/tree.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/lib.rs
Labels: feature

#3869 Fix intra-doc links
  vortex-expr/src/lib.rs
Labels: chore

#3873 fix: Fuzzer does not generate filter on struct
  vortex-expr/src/arbitrary.rs
Labels: chore

#3875 Arrow iterator conversions
  vortex-array/Cargo.toml
  vortex-array/src/arrow/iter.rs
  vortex-array/src/arrow/mod.rs
  vortex-python/src/dataset.rs
  vortex-python/src/file.rs
  vortex-python/src/iter/mod.rs
  vortex-python/src/lib.rs
Labels: feature

#3870 chore[bench]: move tpcds into new benchmark format
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/bin/tpcds.rs
  bench-vortex/src/clickbench/clickbench_benchmark.rs
  bench-vortex/src/clickbench/clickbench_data.rs
  bench-vortex/src/clickbench/mod.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/df/mod.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/tpcds/mod.rs
  bench-vortex/src/tpcds/tpcds_benchmark.rs
  bench-vortex/src/tpch/duckdb.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/src/tpch/tpch_benchmark.rs
Labels: benchmark, chore

#3871 chore: Consitent naming for display functions
  encodings/dict/src/display.rs
  fuzz/fuzz_targets/array_ops.rs
  fuzz/fuzz_targets/file_io.rs
  fuzz/src/error.rs
  vortex-array/src/array/display/mod.rs
  vortex-array/src/array/display/tree.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/compute/mod.rs
  vortex-btrblocks/src/float.rs
  vortex-btrblocks/src/integer.rs
  vortex-btrblocks/src/lib.rs
  vortex-btrblocks/src/string.rs
  vortex-python/python/vortex/_lib/arrays.pyi
  vortex-python/src/arrays/mod.rs
  vortex-tui/src/browse/ui/layouts.rs
  vortex-tui/src/tree.rs
  wasm-test/src/main.rs
Labels: chore

#3863 feature: multi-file-scan thread-safe iterator
  Cargo.lock
  Cargo.toml
  vortex-datafusion/src/persistent/opener.rs
  vortex-duckdb/.gitignore
  vortex-duckdb/src/exporter/mod.rs
  vortex-duckdb/src/scan.rs
  vortex-duckdb/src/vortex_e2e_tests.rs
  vortex-ffi/src/file.rs
  vortex-file/Cargo.toml
  vortex-file/src/file.rs
  vortex-file/src/lib.rs
  vortex-file/src/strategy.rs
  vortex-file/src/tests.rs
  vortex-file/src/writer.rs
  vortex-layout/src/executor.rs
  vortex-layout/src/layouts/compact.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/lib.rs
  vortex-python/src/file.rs
  vortex-scan/Cargo.toml
  vortex-scan/src/lib.rs
  vortex-scan/src/multi_scan.rs
  vortex-scan/src/row_mask.rs
  vortex-scan/src/selection.rs
  vortex-scan/src/split_by.rs
  vortex-scan/src/tasks.rs
  vortex-tui/Cargo.toml
  vortex-tui/src/browse/app.rs
  vortex-tui/src/browse/ui/layouts.rs
  vortex-tui/src/browse/ui/segments.rs
  vortex-tui/src/convert.rs
  vortex-tui/src/segments.rs
  vortex/Cargo.toml
  vortex/src/lib.rs
Labels: feature

#3888 duckdb build script http timeout
  vortex-duckdb/build.rs
Labels: chore

#3881 feat: build with stable rust
  .github/actions/setup-rust/action.yml
  .github/workflows/ci.yml
  .github/workflows/fuzz.yml
  Cargo.lock
  Cargo.toml
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/tpch/tpch_benchmark.rs
  clippy.toml
  encodings/alp/src/alp/mod.rs
  encodings/fastlanes/src/bitpacking/compute/filter.rs
  encodings/fastlanes/src/delta/compress.rs
  encodings/fastlanes/src/lib.rs
  encodings/fsst/src/canonical.rs
  encodings/sequence/src/array.rs
  encodings/zstd/src/array.rs
  fuzz/fuzz_targets/array_ops.rs
  fuzz/fuzz_targets/file_io.rs
  fuzz/src/error.rs
  fuzz/src/lib.rs
  rust-toolchain.toml
  rustfmt.toml
  vortex-array/Cargo.toml
  vortex-array/build.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/arrays/chunked/decode.rs
  vortex-array/src/arrays/decimal/serde.rs
  vortex-array/src/arrays/primitive/accessor.rs
  vortex-array/src/arrays/primitive/compute/take/mod.rs
  vortex-array/src/arrays/varbin/accessor.rs
  vortex-array/src/builders/varbinview.rs
  vortex-array/src/lib.rs
  vortex-buffer/src/buffer.rs
  vortex-buffer/src/buffer_mut.rs
  vortex-buffer/src/lib.rs
  vortex-buffer/src/spec_extend.rs
  vortex-buffer/src/trusted_len.rs
  vortex-dtype/src/struct_.rs
  vortex-duckdb/src/duckdb/connection.rs
  vortex-duckdb/src/duckdb/data_chunk.rs
  vortex-duckdb/src/duckdb/database.rs
  vortex-duckdb/src/duckdb/expr.rs
  vortex-duckdb/src/duckdb/query_result.rs
  vortex-duckdb/src/duckdb/table_filter.rs
  vortex-duckdb/src/duckdb/table_function/mod.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/vortex_e2e_tests.rs
  vortex-error/src/lib.rs
  vortex-error/src/python.rs
  vortex-expr/src/transform/annotations.rs
  vortex-expr/src/transform/partition.rs
  wasm-test/Cargo.lock
Labels: feature

#3896 Use ptr::default in Rust 1.88
  Cargo.toml
  vortex-ffi/src/array.rs
  vortex-ffi/src/array_iterator.rs
  vortex-ffi/src/error.rs
  vortex-ffi/src/file.rs
  vortex-ffi/src/sink.rs
Labels: chore

#3894 fix: `DictMaskEvaluation` to respect validity
  vortex-layout/src/layouts/dict/reader.rs
Labels: fix

#3907 chore[docs]: deny missing_docs on vortex-scalar, vortex-utils, & vortex-flatbuffers
  vortex-flatbuffers/src/lib.rs
  vortex-scalar/src/arbitrary/decimal.rs
  vortex-scalar/src/arbitrary/mod.rs
  vortex-scalar/src/bigint/bigcast.rs
  vortex-scalar/src/bigint/mod.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/bool.rs
  vortex-scalar/src/decimal.rs
  vortex-scalar/src/extension.rs
  vortex-scalar/src/lib.rs
  vortex-scalar/src/list.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/pvalue.rs
  vortex-scalar/src/scalar_type.rs
  vortex-scalar/src/scalar_value/mod.rs
  vortex-scalar/src/struct_.rs
  vortex-scalar/src/utf8.rs
  vortex-utils/src/aliases/hash_map.rs
  vortex-utils/src/aliases/hash_set.rs
  vortex-utils/src/aliases/mod.rs
  vortex-utils/src/lib.rs
Labels: documentation, chore

#3908 chore: exclude arbitrary from coverage
  .github/workflows/ci.yml
Labels: chore

#3901 feat: duckdb global conversion cache
  Cargo.lock
  vortex-duckdb/Cargo.toml
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/exporter/cache.rs
  vortex-duckdb/src/exporter/dict.rs
  vortex-duckdb/src/exporter/mod.rs
  vortex-duckdb/src/exporter/run_end.rs
  vortex-duckdb/src/scan.rs
  vortex-scan/src/multi_scan.rs
Labels: feature

#3914 chore: Fix fmt-failing duckdb code
  vortex-duckdb/src/exporter/cache.rs
  vortex-duckdb/src/exporter/dict.rs
  vortex-duckdb/src/scan.rs
Labels: chore

#3911 chore: Migrate NNF doctests to actual tests
  Cargo.lock
  vortex-expr/Cargo.toml
  vortex-expr/src/forms/nnf.rs
Labels: chore

#3912 fix: duckdb scan cleanup
  vortex-scan/src/multi_scan.rs
Labels: fix

#3920 fix: duckdb multithreaded scan
  vortex-duckdb/src/scan.rs
Labels: fix

#3921 Add BtrBlocksCompressor decision tree
  REUSE.toml
  vortex-btrblocks/Cargo.toml
  vortex-btrblocks/README.md
  vortex-btrblocks/decision-tree.gv
  vortex-btrblocks/decision-tree.svg
Labels: documentation, chore

#3923 chore: Enable workspace lints on vortex-scan
  Cargo.lock
  vortex-scan/Cargo.toml
  vortex-scan/src/multi_scan.rs
Labels: chore

#3924 fix: nbytes returns a u64
  encodings/pco/src/test.rs
  encodings/zstd/src/array.rs
  encodings/zstd/src/test.rs
  vortex-array/src/array/display/tree.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/arrays/chunked/array.rs
  vortex-array/src/stats/array.rs
  vortex-layout/src/layouts/buffered.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-python/src/arrays/mod.rs
  vortex-python/src/arrays/native.rs
Labels: fix

#3940 Update workstealing PR
  vortex-scan/src/multi_scan.rs
Labels: performance

#3938 perf: fine tune workstealing
  vortex-duckdb/src/scan.rs
  vortex-scan/src/multi_scan.rs
Labels: performance

#3941 Add cardinality callback to DuckDB TableFunction
  vortex-duckdb/cpp/CMakeLists.txt
  vortex-duckdb/cpp/include/duckdb_vx/table_function.h
  vortex-duckdb/cpp/table_function.cpp
  vortex-duckdb/src/duckdb/table_function/cardinality.rs
  vortex-duckdb/src/duckdb/table_function/mod.rs
  vortex-duckdb/src/scan.rs
Labels: performance

#3947 chore: Propagate traces to task executor and a bunch of other places
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/bin/public_bi.rs
  bench-vortex/src/clickbench/clickbench_data.rs
  vortex-datafusion/src/persistent/format.rs
  vortex-file/Cargo.toml
  vortex-layout/Cargo.toml
  vortex-layout/src/executor.rs
  vortex-metrics/src/macros.rs
Labels: chore

#3926 feat: Refactor traversal logic
  vortex-expr/src/forms/nnf.rs
  vortex-expr/src/transform/field_mask.rs
  vortex-expr/src/transform/mod.rs
  vortex-expr/src/transform/partition.rs
  vortex-expr/src/transform/remove_merge.rs
  vortex-expr/src/transform/remove_select.rs
  vortex-expr/src/transform/replace.rs
  vortex-expr/src/transform/simplify.rs
  vortex-expr/src/traversal/mod.rs
  vortex-expr/src/traversal/visitor.rs
Labels: feature

#3966 DuckDB Dynamic Expressions
  Cargo.lock
  vortex-array/src/compute/compare.rs
  vortex-duckdb/cpp/include/duckdb_vx/table_filter.h
  vortex-duckdb/cpp/table_filter.cpp
  vortex-duckdb/src/convert/table_filter.rs
  vortex-duckdb/src/duckdb/table_filter.rs
  vortex-duckdb/src/scan.rs
  vortex-expr/Cargo.toml
  vortex-expr/src/exprs/dynamic.rs
  vortex-expr/src/exprs/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-scalar/src/lib.rs
Labels: performance

#3972 feature: Add IsConstant for DecimalBytePartsArray
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/is_constant.rs
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/mod.rs
Labels: feature

#3971 chore: Convert cases of Buffer::extend to using extend_trusted
  Cargo.lock
  encodings/runend/src/compute/take.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-buffer/Cargo.toml
  vortex-buffer/src/buffer.rs
  vortex-buffer/src/trusted_len.rs
Labels: chore

#3979 fix: Prevent compressor from choosing SequenceArray for dictionary codes
  vortex-btrblocks/src/integer.rs
Labels: fix

#3980 chore: duckdb decimal to arrow conversion
  vortex-duckdb/src/convert/vector.rs
  vortex-duckdb/src/exporter/decimal.rs
  vortex-duckdb/src/exporter/mod.rs
Labels: chore

#3985 chore: RunEndArray ends must be unsigned so only enumerate unsigned ptypes for decompression
  encodings/runend/src/compress.rs
Labels: chore

#3984 prevent double stealing
  vortex-scan/src/work_queue.rs
Labels: fix

#3969 fix: correctly expose gen_test_data cxx ffi
  .github/workflows/ci.yml
  vortex-cxx/CMakeLists.txt
  vortex-cxx/build.rs
  vortex-cxx/cpp/tests/basic_test.cpp
  vortex-cxx/examples/.gitignore
  vortex-cxx/examples/CMakeLists.txt
  vortex-cxx/examples/README.md
  vortex-cxx/examples/goldenfiles/example.parquet
  vortex-cxx/examples/hello-vortex.cpp
  vortex-cxx/src/gen_test_data.rs
  vortex-cxx/src/lib.rs
Labels: fix

#3989 chore[duckdb]: scan log info -> trace
  vortex-duckdb/src/scan.rs
Labels: chore

#3986 feat[duckdb]: add file pruning and fix scanner
  vortex-duckdb/src/scan.rs
  vortex-file/src/file.rs
  vortex-scan/src/multi_scan.rs
  vortex-scan/src/work_queue.rs
Labels: feature, fix

#3998 fix: Make NotExpr display more explicit
  vortex-btrblocks/src/string.rs
  vortex-expr/src/exprs/not.rs
  vortex-expr/src/lib.rs
Labels: fix

#3999 chore: Add some tests and docs to layouts and duckdb
  Cargo.lock
  vortex-duckdb/Cargo.toml
  vortex-duckdb/src/convert/dtype.rs
  vortex-layout/src/layouts/zoned/mod.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
Labels: chore

#3973 fix: Pruning expressions check NanCount where appropriate
  .github/workflows/ci.yml
  vortex-array/src/arrays/struct_/mod.rs
  vortex-datafusion/src/persistent/source.rs
  vortex-expr/src/analysis.rs
  vortex-expr/src/exprs/binary.rs
  vortex-expr/src/exprs/get_item.rs
  vortex-expr/src/exprs/literal.rs
  vortex-expr/src/exprs/root.rs
  vortex-expr/src/lib.rs
  vortex-expr/src/pruning/mod.rs
  vortex-expr/src/pruning/pruning_expr.rs
  vortex-file/src/pruning.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
Labels: fix

#4001 fix: increment `num_factories_constructed` on error
  vortex-scan/src/work_queue.rs
Labels: fix

#4004 fix: unify duckdb timestamps on i64
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/convert/vector.rs
  vortex-duckdb/src/duckdb/vector.rs
Labels: fix

#4011 fix[ci]: use cargo +nightly in publish
  .github/workflows/publish.yml
Labels: fix

#4007 chore: unit tests for Arrow conversion
  vortex-array/src/arrow/convert.rs
Labels: chore

#4017 perf[bench]: dont delete duckdb.db between db runs
  bench-vortex/src/engines/ddb/mod.rs
Labels: performance

#4022 chore: optionally delete the duckdb database on engine creation.
  .github/workflows/sql-benchmarks.yml
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/benchmark_trait.rs
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/engines/mod.rs
  bench-vortex/src/tpcds/tpcds_benchmark.rs
Labels: chore

#4014 chore: benchmark individual encoding throughputs
  Cargo.lock
  vortex/Cargo.toml
  vortex/benches/single_encoding_throughput.rs
Labels: chore

#4023 fix: fix sql benchmarks option
  .github/workflows/sql-benchmarks.yml
Labels: fix

#4035 use arc slice for buffers in varbinview
  encodings/dict/src/builders/bytes.rs
  encodings/fsst/src/canonical.rs
  encodings/sparse/src/canonical.rs
  encodings/zstd/src/array.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/arrays/varbinview/compact.rs
  vortex-array/src/arrays/varbinview/compute/cast.rs
  vortex-array/src/arrays/varbinview/compute/mask.rs
  vortex-array/src/arrays/varbinview/compute/take.rs
  vortex-array/src/arrays/varbinview/mod.rs
  vortex-array/src/arrays/varbinview/ops.rs
  vortex-array/src/arrays/varbinview/serde.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/builders/varbinview.rs
Labels: chore

#4037 feature: Add From implementation to the vtable in addition to dedicated trait
  vortex-array/src/vtable/mod.rs
  vortex-expr/src/vtable.rs
  vortex-layout/src/vtable.rs
Labels: feature

#4039 docs: Document all canonical array types
  vortex-array/src/arrays/bool/array.rs
  vortex-array/src/arrays/decimal/mod.rs
  vortex-array/src/arrays/extension/mod.rs
  vortex-array/src/arrays/list/mod.rs
  vortex-array/src/arrays/null/mod.rs
  vortex-array/src/arrays/primitive/mod.rs
  vortex-array/src/arrays/struct_/mod.rs
  vortex-array/src/arrays/varbinview/mod.rs
Labels: documentation, chore

#3992 feat: teach SparseArray to canonicalize lists
  encodings/sparse/src/canonical.rs
Labels: feature

#4041 [chore] add filter conformance test & fill existing conformance testing gaps
  encodings/alp/src/alp/compute/filter.rs
  encodings/alp/src/alp/compute/mask.rs
  encodings/alp/src/alp/compute/mod.rs
  encodings/alp/src/alp/compute/take.rs
  encodings/alp/src/alp_rd/compute/filter.rs
  encodings/alp/src/alp_rd/compute/mask.rs
  encodings/bytebool/src/compute.rs
  encodings/datetime-parts/src/compute/filter.rs
  encodings/decimal-byte-parts/src/decimal_byte_parts/compute/filter.rs
  encodings/dict/src/compute/binary_numeric.rs
  encodings/dict/src/compute/mod.rs
  encodings/fastlanes/src/bitpacking/compute/filter.rs
  encodings/fastlanes/src/for/compute/mod.rs
  encodings/fsst/src/compute/filter.rs
  encodings/runend/src/compute/binary_numeric.rs
  encodings/runend/src/compute/mod.rs
  encodings/sparse/src/compute/mod.rs
  encodings/zigzag/src/compute.rs
  vortex-array/src/arrays/bool/array.rs
  vortex-array/src/arrays/bool/compute/filter.rs
  vortex-array/src/arrays/bool/compute/mask.rs
  vortex-array/src/arrays/chunked/array.rs
  vortex-array/src/arrays/chunked/compute/filter.rs
  vortex-array/src/arrays/chunked/compute/mask.rs
  vortex-array/src/arrays/constant/compute/mod.rs
  vortex-array/src/arrays/decimal/compute/filter.rs
  vortex-array/src/arrays/extension/compute/mod.rs
  vortex-array/src/arrays/list/compute/mod.rs
  vortex-array/src/arrays/null/compute.rs
  vortex-array/src/arrays/primitive/compute/filter.rs
  vortex-array/src/arrays/primitive/compute/mask.rs
  vortex-array/src/arrays/primitive/mod.rs
  vortex-array/src/arrays/struct_/compute/mod.rs
  vortex-array/src/arrays/varbin/compute/filter.rs
  vortex-array/src/arrays/varbin/compute/mask.rs
  vortex-array/src/arrays/varbinview/compute/filter.rs
  vortex-array/src/arrays/varbinview/compute/mask.rs
  vortex-array/src/arrays/varbinview/compute/mod.rs
  vortex-array/src/compute/conformance/binary_numeric.rs
  vortex-array/src/compute/conformance/filter.rs
  vortex-array/src/compute/conformance/mask.rs
  vortex-array/src/compute/conformance/mod.rs
Labels: chore

#4031 zip compute function
  vortex-array/src/compute/mod.rs
  vortex-array/src/compute/zip.rs
Labels: feature

#4036 varbinview builder buffer deduplication
  vortex-array/src/arrays/varbinview/mod.rs
  vortex-array/src/builders/varbinview.rs
Labels: performance

#4045 [chore] use rstest for filter & mask conformance test harnesses
  encodings/alp/src/alp/compute/filter.rs
  encodings/alp/src/alp/compute/mask.rs
  vortex-array/src/arrays/bool/compute/filter.rs
  vortex-array/src/arrays/bool/compute/mask.rs
  vortex-array/src/arrays/chunked/compute/filter.rs
  vortex-array/src/arrays/chunked/compute/mask.rs
  vortex-array/src/arrays/primitive/compute/filter.rs
  vortex-array/src/arrays/primitive/compute/mask.rs
  vortex-array/src/compute/conformance/consistency.rs
  vortex-array/src/compute/conformance/filter.rs
  vortex-array/src/compute/conformance/mask.rs
  vortex-array/src/compute/conformance/mod.rs
Labels: chore

#3356 Clean up stats propagation for slicing
  encodings/pco/src/array.rs
  encodings/zstd/src/array.rs
  encodings/zstd/src/test.rs
  vortex-array/src/array/convert.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/array/statistics.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/arrays/constant/compute/sum.rs
  vortex-array/src/arrays/constant/mod.rs
  vortex-array/src/arrays/list/compute/take.rs
  vortex-array/src/arrays/primitive/compute/is_constant.rs
  vortex-array/src/arrays/primitive/compute/sum.rs
  vortex-array/src/compute/is_constant.rs
  vortex-array/src/compute/min_max.rs
  vortex-array/src/compute/sum.rs
  vortex-array/src/stats/array.rs
  vortex-array/src/stats/mod.rs
  vortex-array/src/stats/stats_set.rs
  vortex-dtype/src/ptype.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/scalar_value/mod.rs
  vortex-tui/src/browse/ui/layouts.rs
Labels: chore

#4044 fix tui segment display for auxiliary children
  vortex-tui/src/browse/mod.rs
  vortex-tui/src/browse/ui/segments.rs
Labels: fix

#4059 test: block_in_place
  vortex-scan/src/multi_thread.rs
Labels: chore

#4053 chore: add `into_cpu_stream`
  vortex-datafusion/Cargo.toml
  vortex-datafusion/src/persistent/opener.rs
  vortex-file/Cargo.toml
  vortex-file/src/tests.rs
  vortex-scan/src/lib.rs
Labels: chore

#4054 varbinview zip kernel
  vortex-array/src/arrays/varbinview/compute/mod.rs
  vortex-array/src/arrays/varbinview/compute/zip.rs
  vortex-array/src/compute/zip.rs
Labels: performance

#4066 chore: cleanup commented-out code in vortex-expr
  vortex-expr/src/registry.rs
Labels: chore

#4070 fix: compress benchmarks opts doesnt conflict with output
  bench-vortex/src/bin/compress.rs
Labels: fix

#4072 Fix prefetch accounting
  vortex-file/src/driver.rs
Labels: fix

#4077 feat: Add serialization support for Select expression
  vortex-expr/src/exprs/select.rs
  vortex-expr/src/proto.rs
  vortex-proto/proto/expr.proto
  vortex-proto/src/generated/vortex.expr.rs
Labels: feature

#4067 chore: Enable polarsignals diffs on benchmarks
  .github/workflows/bench-pr.yml
  .github/workflows/bench.yml
  .github/workflows/sql-benchmarks.yml
  .github/workflows/sql-pr.yml
Labels: chore

#4079 chore: rewrite the benchmark website
  benchmarks-website/code.js
  benchmarks-website/index.html
  benchmarks-website/style.css
  benchmarks-website/vortex_black_nobg.svg
Labels: chore
