Repository vortex-data/vortex, pull requests merged in 2025-08, with the labels that each got.

#4088 chore: fix some typos
  vortex-duckdb/cpp/include/duckdb_vx/expr.h
  vortex-duckdb/src/convert/expr.rs
  vortex-duckdb/src/convert/table_filter.rs
  vortex-ffi/cinclude/vortex.h
  vortex-ffi/src/dtype.rs
Labels: chore

#4095 fix[duckdb]: make batch number unique over all threads
  vortex-duckdb/src/scan.rs
Labels: fix

#4098 chore[bench-site]: add aggregates of each group to bench site
  benchmarks-website/code.js
  benchmarks-website/style.css
Labels: chore

#4099 chore[bench-site]: bench site CSS cleanup
  benchmarks-website/style.css
Labels: chore

#4102 chore[bench-site]: more mobile fixes
  benchmarks-website/code.js
  benchmarks-website/index.html
  benchmarks-website/style.css
Labels: chore

#4104 perf[duckdb]: add file footer caching
  vortex-duckdb/build.rs
  vortex-duckdb/cpp/CMakeLists.txt
  vortex-duckdb/cpp/client_context.cpp
  vortex-duckdb/cpp/include/duckdb_vx.h
  vortex-duckdb/cpp/include/duckdb_vx/client_context.h
  vortex-duckdb/cpp/include/duckdb_vx/object_cache.h
  vortex-duckdb/cpp/include/duckdb_vx/table_function.h
  vortex-duckdb/cpp/object_cache.cpp
  vortex-duckdb/cpp/table_function.cpp
  vortex-duckdb/src/duckdb/client_context.rs
  vortex-duckdb/src/duckdb/connection.rs
  vortex-duckdb/src/duckdb/footer_cache.rs
  vortex-duckdb/src/duckdb/mod.rs
  vortex-duckdb/src/duckdb/object_cache.rs
  vortex-duckdb/src/duckdb/table_function/bind.rs
  vortex-duckdb/src/duckdb/table_function/init.rs
  vortex-duckdb/src/duckdb/table_function/mod.rs
  vortex-duckdb/src/e2e_test/mod.rs
  vortex-duckdb/src/e2e_test/object_cache_test.rs
  vortex-duckdb/src/e2e_test/vortex_scan_test.rs
  vortex-duckdb/src/lib.rs
  vortex-duckdb/src/scan.rs
Labels: performance

#4108 perf[vortex-array]: use all_valid instead of `invalid_count() == 0`
  vortex-array/src/compute/fill_null.rs
  vortex-array/src/compute/is_sorted.rs
Labels: performance

#4107 TransposedStream in struct writer to wake other potentially waiting streams
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-tui/src/convert.rs
Labels: fix

#4117 fix[duckdb]: use executor in ddb writer
  vortex-duckdb/src/copy.rs
Labels: fix

#4120 chore: Add workflow to minimize fuzz corpuses
  .github/workflows/minimize_fuzz_corpus.yml
Labels: chore

#4121 fix[duckdb]: glob expansion canonicalize input path
  vortex-duckdb/src/utils/glob.rs
Labels: fix

#4123 chore: move clippy cpp.rs allow list to build.rs
  vortex-duckdb/build.rs
  vortex-duckdb/src/lib.rs
  vortex-duckdb/src/utils/glob.rs
Labels: chore

#4124 chore: fuzz only uploads new corpus if it hasn't been updated in the meantime
  .github/workflows/fuzz.yml
Labels: chore

#4114 chore: improve consistency tests
  vortex-array/src/compute/conformance/consistency.rs
Labels: chore

#4139 feat: Require expressions to be `Eq`
  vortex-expr/src/vtable.rs
Labels: feature

#4141 fix: pr benchmark results
  bench-vortex/src/datasets/mod.rs
  scripts/compare-benchmark-jsons.py
Labels: fix

#4147 tests: test writing empty file in PyVortex
  vortex-python/test/test_file.py
Labels: pyvortex, chore

#4149 refactor the LayoutStrategy
  bench-vortex/src/compress/vortex.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/public_bi.rs
  docs/concepts/layouts.md
  encodings/sequence/src/serde.rs
  vortex-btrblocks/src/lib.rs
  vortex-duckdb/src/copy.rs
  vortex-file/src/strategy.rs
  vortex-file/src/writer.rs
  vortex-layout/src/layouts/buffered.rs
  vortex-layout/src/layouts/chunked/reader.rs
  vortex-layout/src/layouts/chunked/writer.rs
  vortex-layout/src/layouts/compact.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/repartition.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-layout/src/layouts/struct_/writer.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-layout/src/layouts/zoned/writer.rs
  vortex-layout/src/lib.rs
  vortex-layout/src/strategy.rs
  vortex-layout/src/writer.rs
  vortex-tui/src/convert.rs
  vortex/src/lib.rs
Labels: feature

#4135 Only coerce scalar values when necessary
  vortex-scalar/src/lib.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/proto.rs
  vortex-scalar/src/pvalue.rs
Labels: fix

#4145 chore: improve vortex-scalar tests, reorganize module structure
  Cargo.lock
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/builders/mod.rs
  vortex-datafusion/src/convert/scalars.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-jni/src/array.rs
  vortex-python/src/scalar/into_py.rs
  vortex-scalar/Cargo.toml
  vortex-scalar/src/arrow/mod.rs
  vortex-scalar/src/arrow/tests.rs
  vortex-scalar/src/bigint/mod.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/bool.rs
  vortex-scalar/src/decimal/mod.rs
  vortex-scalar/src/decimal/tests.rs
  vortex-scalar/src/decimal/value.rs
  vortex-scalar/src/lib.rs
  vortex-scalar/src/list.rs
  vortex-scalar/src/null.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/scalar_type.rs
  vortex-scalar/src/scalar_value/binary.rs
  vortex-scalar/src/struct_.rs
  vortex-scalar/src/tests/consistency.rs
  vortex-scalar/src/tests/core.rs
  vortex-scalar/src/tests/mod.rs
  vortex-scalar/src/tests/round_trip.rs
  vortex-scalar/src/utf8.rs
Labels: chore

#4159 chore: Bump msrv to 1.89
  Cargo.toml
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/engines/df/mod.rs
  encodings/alp/src/alp/ops.rs
  encodings/bytebool/src/array.rs
  encodings/fastlanes/src/bitpacking/compute/is_constant.rs
  encodings/fastlanes/src/bitpacking/compute/take.rs
  encodings/fastlanes/src/bitpacking/ops.rs
  encodings/fastlanes/src/delta/mod.rs
  encodings/fastlanes/src/for/compute/compare.rs
  encodings/sparse/src/lib.rs
  rust-toolchain.toml
  vortex-array/src/arrays/bool/array.rs
  vortex-array/src/arrays/decimal/mod.rs
  vortex-array/src/arrays/primitive/mod.rs
  vortex-array/src/arrow/compute/to_arrow/mod.rs
  vortex-array/src/compute/between.rs
  vortex-array/src/compute/conformance/cast.rs
  vortex-array/src/compute/conformance/consistency.rs
  vortex-array/src/compute/conformance/take.rs
  vortex-array/src/compute/min_max.rs
  vortex-btrblocks/src/lib.rs
  vortex-buffer/src/buffer.rs
  vortex-datafusion/src/persistent/metrics.rs
  vortex-datafusion/src/persistent/opener.rs
  vortex-duckdb/src/duckdb/footer_cache.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/scan.rs
  vortex-duckdb/src/utils/glob.rs
  vortex-error/src/ext.rs
  vortex-error/src/lib.rs
  vortex-expr/src/transform/simplify.rs
  vortex-expr/src/traversal/mod.rs
  vortex-layout/src/executor.rs
  vortex-layout/src/segments/events.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/bool.rs
  vortex-scalar/src/extension.rs
  vortex-scalar/src/utf8.rs
  vortex-scan/src/lib.rs
  vortex-tui/src/browse/mod.rs
Labels: chore

#4162 Support exporting Arrow RunArray to Vortex
  Cargo.lock
  encodings/runend/Cargo.toml
  encodings/runend/src/array.rs
  encodings/runend/src/arrow.rs
  encodings/runend/src/lib.rs
  encodings/runend/src/ops.rs
  vortex/Cargo.toml
Labels: feature

#4152 ScalarValue operations must go via Scalar
  encodings/datetime-parts/src/compute/take.rs
  encodings/fastlanes/src/for/compress.rs
  vortex-array/src/array/mod.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/compress.rs
  vortex-array/src/compute/is_constant.rs
  vortex-array/src/compute/min_max.rs
  vortex-array/src/compute/sum.rs
  vortex-array/src/compute/take.rs
  vortex-array/src/stats/array.rs
  vortex-array/src/stats/flatbuffers.rs
  vortex-array/src/stats/mod.rs
  vortex-array/src/stats/provider.rs
  vortex-array/src/stats/stats_set.rs
  vortex-btrblocks/src/integer/stats.rs
  vortex-datafusion/src/persistent/format.rs
  vortex-file/src/pruning.rs
  vortex-layout/src/layouts/flat/writer.rs
  vortex-layout/src/layouts/zoned/builder.rs
  vortex-layout/src/layouts/zoned/zone_map.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/decimal/value.rs
  vortex-scalar/src/list.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/scalar_value.rs
  vortex-scalar/src/scalar_value/binary.rs
  vortex-scalar/src/scalar_value/bool.rs
  vortex-scalar/src/scalar_value/decimal.rs
  vortex-scalar/src/scalar_value/list.rs
  vortex-scalar/src/scalar_value/primitive.rs
  vortex-scalar/src/scalar_value/utf8.rs
  vortex-scalar/src/tests/round_trip.rs
  vortex-scalar/src/utf8.rs
Labels: fix

#4089 Inline the logic of the filter layout reader
  Cargo.lock
  vortex-layout/Cargo.toml
  vortex-layout/src/layouts/filter.rs
  vortex-layout/src/layouts/mod.rs
  vortex-layout/src/layouts/zoned/reader.rs
  vortex-scan/Cargo.toml
  vortex-scan/src/filter.rs
  vortex-scan/src/lib.rs
  vortex-scan/src/tasks.rs
Labels: feature

#4155 chore[bench-website]: add back tpc-ds to query_bench
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/tpch_l_comment.rs
  bench-vortex/src/tpcds/duckdb.rs
  bench-vortex/src/tpcds/mod.rs
  bench-vortex/src/tpcds/tpcds_benchmark.rs
  bench-vortex/src/tpch/duckdb.rs
  bench-vortex/src/tpch/mod.rs
  bench-vortex/src/tpch/tpch_benchmark.rs
  bench-vortex/src/tpch/tpchgen.rs
Labels: chore

#4172 fix[duckdb]: validity ref u64 not u8
  vortex-duckdb/src/duckdb/vector.rs
Labels: fix

#4169 feat: teach Vortex how to export list arrays to duckdb
  vortex-duckdb/src/convert/vector.rs
  vortex-duckdb/src/duckdb/logical_type.rs
  vortex-duckdb/src/duckdb/vector.rs
  vortex-duckdb/src/exporter/bool.rs
  vortex-duckdb/src/exporter/constant.rs
  vortex-duckdb/src/exporter/decimal.rs
  vortex-duckdb/src/exporter/list.rs
  vortex-duckdb/src/exporter/mod.rs
  vortex-duckdb/src/exporter/primitive.rs
  vortex-duckdb/src/exporter/varbinview.rs
Labels: feature

#4182 fix: Fix some minor typos and remove the "single-file" feature from clickbench
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/clickbench/clickbench_benchmark.rs
  bench-vortex/src/clickbench/clickbench_data.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
Labels: fix

#4170 feat[duckdb]: support more operators
  bench-vortex/tpcds/90.sql
  vortex-duckdb/src/convert/expr.rs
Labels: feature

#4199 fix[bench-website]: add tpc-ds to bench website
  benchmarks-website/data-worker.js
Labels: fix

#4201 fix: small resource leak in vortex-io, plus test improvements
  CLAUDE.md
  Cargo.lock
  vortex-io/Cargo.toml
  vortex-io/src/dispatcher/compio.rs
  vortex-io/src/dispatcher/mod.rs
  vortex-io/src/io_buf.rs
  vortex-io/src/limit.rs
  vortex-io/src/object_store.rs
  vortex-io/src/read.rs
  vortex-io/src/write.rs
Labels: fix

#4204 chore: improve vortex-dtype test coverage
  vortex-array/src/arrays/struct_/mod.rs
  vortex-dtype/src/arrow.rs
  vortex-dtype/src/decimal.rs
  vortex-dtype/src/field_mask.rs
  vortex-dtype/src/nullability.rs
  vortex-dtype/src/serde/flatbuffers/mod.rs
  vortex-dtype/src/serde/flatbuffers/project.rs
  vortex-dtype/src/serde/proto.rs
  vortex-dtype/src/struct_.rs
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/convert/vector.rs
  vortex-python/src/dtype/factory.rs
Labels: chore

#4213 chore: Fix random-access series colours and delete dead code from benchmarking website
  benchmarks-website/chart-worker.js
  benchmarks-website/code.js
  benchmarks-website/config.js
  benchmarks-website/worker-manager.js
Labels: chore

#4212 feat: Expose various expr transformations directly instead of through module
  vortex-expr/src/transform/mod.rs
  vortex-layout/src/layouts/partitioned.rs
  vortex-layout/src/layouts/row_idx/mod.rs
  vortex-layout/src/layouts/struct_/reader.rs
  vortex-scan/src/lib.rs
Labels: feature

#4217 chore: sequential consistency in vortex-scan
  vortex-scan/src/work_queue.rs
Labels: chore

#4225 fix: runend decompress benchmarks
  encodings/runend/benches/run_end_compress.rs
Labels: fix

#4227 fix: Correctly convert arrow temporal arrays with timezone
  vortex-array/src/arrow/convert.rs
Labels: fix

#4228 chore: expand runend decompress benchmarks
  encodings/runend/benches/run_end_compress.rs
Labels: chore

#4232 Fix: Return currect field names in `SelectExpr::as_include`
  vortex-expr/src/exprs/select.rs
Labels: fix

#4234 feature: Add TryFrom impls for owned scalars to values
  vortex-scalar/src/list.rs
  vortex-scalar/src/utf8.rs
Labels: feature

#4233 docs: fill in missing javadoc
  java/vortex-jni/src/main/java/dev/vortex/DateTimeUtil.java
  java/vortex-jni/src/main/java/dev/vortex/api/Array.java
  java/vortex-jni/src/main/java/dev/vortex/api/ArrayIterator.java
  java/vortex-jni/src/main/java/dev/vortex/api/DType.java
  java/vortex-jni/src/main/java/dev/vortex/api/Expression.java
  java/vortex-jni/src/main/java/dev/vortex/api/File.java
  java/vortex-jni/src/main/java/dev/vortex/api/Files.java
  java/vortex-jni/src/main/java/dev/vortex/api/ScanOptions.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/Binary.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/GetItem.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/Literal.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/Not.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/Root.java
  java/vortex-jni/src/main/java/dev/vortex/api/expressions/Unknown.java
  java/vortex-jni/src/main/java/dev/vortex/api/proto/DTypes.java
  java/vortex-jni/src/main/java/dev/vortex/api/proto/EndianUtils.java
  java/vortex-jni/src/main/java/dev/vortex/api/proto/Expressions.java
  java/vortex-jni/src/main/java/dev/vortex/api/proto/Scalars.java
  java/vortex-jni/src/main/java/dev/vortex/api/proto/TemporalMetadatas.java
  java/vortex-jni/src/main/java/dev/vortex/arrow/ArrowAllocation.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeLoader.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeLogging.java
  java/vortex-jni/src/test/java/dev/vortex/api/TestMinimal.java
  java/vortex-spark/src/main/java/dev/vortex/spark/ArrowUtils.java
  java/vortex-spark/src/main/java/dev/vortex/spark/VortexDataSourceV2.java
  java/vortex-spark/src/main/java/dev/vortex/spark/VortexFilePartition.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/ReaderFactory.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexArrowColumnVector.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexBatchExec.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexColumnarBatch.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexColumnarBatchIterator.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexScan.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexScanBuilder.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexTable.java
Labels: documentation, chore

#4236 fix[bench-site]: Compression Size group missing charts
  benchmarks-website/data-worker.js
Labels: fix

#4224 feat(c++): support passing filter and projection expression in scan
  .github/workflows/ci.yml
  Cargo.lock
  vortex-cxx/CMakeLists.txt
  vortex-cxx/Cargo.toml
  vortex-cxx/cpp/include/vortex.hpp
  vortex-cxx/cpp/include/vortex/dtype.hpp
  vortex-cxx/cpp/include/vortex/expr.hpp
  vortex-cxx/cpp/include/vortex/file.hpp
  vortex-cxx/cpp/include/vortex/scalar.hpp
  vortex-cxx/cpp/include/vortex/scan.hpp
  vortex-cxx/cpp/include/vortex/write_options.hpp
  vortex-cxx/cpp/src/dtype.cpp
  vortex-cxx/cpp/src/expr.cpp
  vortex-cxx/cpp/src/file.cpp
  vortex-cxx/cpp/src/scalar.cpp
  vortex-cxx/cpp/src/scan.cpp
  vortex-cxx/cpp/src/scan_impl.hpp
  vortex-cxx/cpp/src/write_options.cpp
  vortex-cxx/cpp/tests/basic_test.cpp
  vortex-cxx/src/dtype.rs
  vortex-cxx/src/expr.rs
  vortex-cxx/src/lib.rs
  vortex-cxx/src/read.rs
  vortex-cxx/src/scalar.rs
  vortex-cxx/src/write.rs
Labels: feature

#4239 feat: Make FieldNames comparison more ergonomic
  vortex-array/src/arrays/struct_/mod.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/struct_.rs
  vortex-expr/src/exprs/merge.rs
  vortex-expr/src/exprs/pack.rs
  vortex-python/src/scalar/factory.rs
  vortex-scalar/src/struct_.rs
Labels: feature

#4237 chore[vortex-array]: facilitate third-party ToArrowKernel implementations
  vortex-array/src/arrow/mod.rs
  vortex-dtype/src/arrow.rs
Labels: chore

#4251 feat: Remove 'parquet' feature and some other dependency bloat
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  encodings/decimal-byte-parts/Cargo.toml
  encodings/pco/Cargo.toml
  encodings/pco/src/array.rs
  encodings/sequence/Cargo.toml
  encodings/sparse/Cargo.toml
  vortex-array/Cargo.toml
  vortex-array/src/arrays/varbin/canonical.rs
  vortex-cxx/Cargo.toml
  vortex-duckdb/Cargo.toml
  vortex-error/Cargo.toml
  vortex-error/src/lib.rs
  vortex-file/Cargo.toml
  vortex-io/Cargo.toml
  vortex-layout/Cargo.toml
  vortex-scan/Cargo.toml
  vortex-tui/Cargo.toml
  vortex-tui/src/convert.rs
  vortex/Cargo.toml
  vortex/src/lib.rs
Labels: feature

#4255 feat: implement `Display` for `StructFields`
  vortex-dtype/src/struct_.rs
Labels: feature

#4246 feat[spark]: write support in VortexDataSourceV2
  Cargo.lock
  Cargo.toml
  java/gradle/wrapper/gradle-wrapper.properties
  java/testfiles/Cargo.lock
  java/versions.lock
  java/vortex-jni/build.gradle.kts
  java/vortex-jni/src/main/java/dev/vortex/api/DType.java
  java/vortex-jni/src/main/java/dev/vortex/api/VortexWriter.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIArray.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIArrayIterator.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIDType.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIFile.java
  java/vortex-jni/src/main/java/dev/vortex/jni/JNIWriter.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeDTypeMethods.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeFileMethods.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeLoader.java
  java/vortex-jni/src/main/java/dev/vortex/jni/NativeWriterMethods.java
  java/vortex-jni/src/test/java/dev/vortex/jni/JNIWriterTest.java
  java/vortex-spark/build.gradle.kts
  java/vortex-spark/src/main/java/dev/vortex/spark/SparkTypes.java
  java/vortex-spark/src/main/java/dev/vortex/spark/VortexDataSourceV2.java
  java/vortex-spark/src/main/java/dev/vortex/spark/VortexTable.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexBatchExec.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexScan.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexScanBuilder.java
  java/vortex-spark/src/main/java/dev/vortex/spark/read/VortexTable.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/SparkToArrowSchema.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexBatchWrite.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexDataWriter.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexDataWriterFactory.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexWriteBuilder.java
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexWriterCommitMessage.java
  java/vortex-spark/src/test/java/dev/vortex/spark/VortexDataSourceBasicTest.java
  java/vortex-spark/src/test/java/dev/vortex/spark/VortexDataSourceWriteTest.java
  vortex-dtype/src/datetime/temporal.rs
  vortex-dtype/src/datetime/unit.rs
  vortex-file/src/writer.rs
  vortex-jni/Cargo.toml
  vortex-jni/src/array_iter.rs
  vortex-jni/src/dtype.rs
  vortex-jni/src/errors.rs
  vortex-jni/src/file.rs
  vortex-jni/src/lib.rs
  vortex-jni/src/object_store.rs
  vortex-jni/src/writer.rs
Labels: feature

#4238 chore[vortex-expr]: folder docs
  vortex-expr/src/traversal/fold.rs
Labels: chore

#4261 chore: Fix all rustdoc warnings and enforce no warning in CI
  .github/workflows/ci.yml
  vortex-datafusion/src/persistent/source.rs
  vortex-file/src/strategy.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-scan/src/lib.rs
Labels: chore

#4282 Add Display impl for FieldNames
  vortex-dtype/src/dtype.rs
Labels: chore

#4291 chore: `DType` documentation
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/field_names.rs
  vortex-dtype/src/lib.rs
Labels: documentation, chore

#4300 chore: move `field_names` tests to `field_names.rs`
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/field_names.rs
Labels: chore

#4298 Chore: Add list of list tests
  vortex-array/src/arrays/list/mod.rs
  vortex-array/src/arrays/list/tests.rs
Labels: chore

#4304 fix: Remove conversion from usize to scalar
  vortex-scalar/src/lib.rs
  vortex-scalar/src/scalar_type.rs
Labels: fix

#4308 fix: vortex-cxx examples macos build
  vortex-cxx/examples/CMakeLists.txt
Labels: fix

#4303 chore: Make downscale_integer_array a method on PrimitiveArray
  encodings/dict/src/builders/mod.rs
  encodings/runend/src/compress.rs
  vortex-array/src/arrays/primitive/downcast.rs
  vortex-array/src/arrays/primitive/mod.rs
  vortex-array/src/compress.rs
  vortex-array/src/lib.rs
  vortex-btrblocks/src/integer.rs
  vortex-btrblocks/src/lib.rs
  vortex-btrblocks/src/patches.rs
  vortex-btrblocks/src/string.rs
  vortex-btrblocks/src/temporal.rs
Labels: chore

#4306 chore: return lvalue ref for cxx's scanbuilder functions
  vortex-cxx/cpp/include/vortex/expr.hpp
  vortex-cxx/cpp/include/vortex/scan.hpp
  vortex-cxx/cpp/src/scan.cpp
  vortex-cxx/cpp/tests/basic_test.cpp
  vortex-cxx/examples/hello-vortex.cpp
  vortex-cxx/src/lib.rs
  vortex-cxx/src/read.rs
Labels: chore

#4328 chore[bench]: have `--skip-generate` option and only create iterators for tpch when needed
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/tpch/tpchgen.rs
Labels: chore

#4332 Clean up match statements and misc
  vortex-array/src/array/display/mod.rs
  vortex-array/src/arrays/chunked/decode.rs
  vortex-array/src/arrays/constant/compute/sum.rs
  vortex-array/src/arrays/datetime/mod.rs
  vortex-array/src/arrays/decimal/mod.rs
  vortex-array/src/arrays/primitive/compute/take/mod.rs
  vortex-array/src/arrays/varbin/compute/compare.rs
  vortex-array/src/arrays/varbin/compute/min_max.rs
  vortex-array/src/arrays/varbin/compute/mod.rs
  vortex-array/src/arrays/varbin/mod.rs
  vortex-array/src/arrays/varbinview/compact.rs
  vortex-array/src/arrays/varbinview/mod.rs
  vortex-array/src/arrow/compute/to_arrow/varbin.rs
  vortex-array/src/arrow/convert.rs
  vortex-array/src/canonical.rs
  vortex-array/src/compute/conformance/binary_numeric.rs
  vortex-array/src/compute/conformance/consistency.rs
  vortex-array/src/compute/filter.rs
  vortex-array/src/compute/mod.rs
  vortex-array/src/stats/mod.rs
  vortex-array/src/stats/precision.rs
  vortex-array/src/validity.rs
  vortex-dtype/src/arrow.rs
  vortex-dtype/src/datetime/arrow.rs
  vortex-dtype/src/datetime/temporal.rs
  vortex-dtype/src/datetime/unit.rs
  vortex-dtype/src/decimal.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/ptype.rs
  vortex-mask/src/lib.rs
  vortex-mask/src/tests.rs
  vortex-scalar/src/arrow/mod.rs
  vortex-scalar/src/decimal/mod.rs
  vortex-scalar/src/decimal/tests.rs
  vortex-scalar/src/proto.rs
  vortex-scalar/src/pvalue.rs
  vortex-scalar/src/scalar_value.rs
Labels: chore

#4289 chore: pyright
  .github/workflows/ci.yml
  docs/api/python/arrays.rst
  docs/api/python/index.rst
  docs/api/python/type_aliases.rst
  docs/conf.py
  docs/generate_missing_polars_objects_inv.py
  docs/polars.objects.inv
  pyproject.toml
  uv.lock
  vortex-python/clickbench.py
  vortex-python/pyproject.toml
  vortex-python/python/vortex/__init__.py
  vortex-python/python/vortex/_lib/arrays.pyi
  vortex-python/python/vortex/_lib/compress.pyi
  vortex-python/python/vortex/_lib/dataset.pyi
  vortex-python/python/vortex/_lib/expr.pyi
  vortex-python/python/vortex/_lib/file.pyi
  vortex-python/python/vortex/_lib/io.pyi
  vortex-python/python/vortex/_lib/iter.pyi
  vortex-python/python/vortex/_lib/mypy.allowlist
  vortex-python/python/vortex/_lib/registry.pyi
  vortex-python/python/vortex/_lib/scalar.pyi
  vortex-python/python/vortex/_lib/serde.pyi
  vortex-python/python/vortex/arrays.py
  vortex-python/python/vortex/arrow/__init__.py
  vortex-python/python/vortex/arrow/expression.py
  vortex-python/python/vortex/dataset.py
  vortex-python/python/vortex/expr.py
  vortex-python/python/vortex/file.py
  vortex-python/python/vortex/io.py
  vortex-python/python/vortex/polars_.py
  vortex-python/python/vortex/serde.py
  vortex-python/python/vortex/substrait.py
  vortex-python/python/vortex/type_aliases.py
  vortex-python/src/arrays/compressed.rs
  vortex-python/src/arrays/mod.rs
  vortex-python/src/dataset.rs
  vortex-python/src/expr/mod.rs
  vortex-python/src/file.rs
  vortex-python/test/bench.py
  vortex-python/test/conftest.py
  vortex-python/test/test_compress.py
  vortex-python/test/test_dataset.py
  vortex-python/test/test_encodings.py
  vortex-python/test/test_file.py
  vortex-python/test/test_pyarray.py
  vortex-python/test/test_scalar.py
Labels: chore

#4336 feat: teach VortexDataset to filter & document vortex.expr.*
  docs/api/python/expr.rst
  docs/conf.py
  vortex-python/python/vortex/_lib/expr.pyi
  vortex-python/python/vortex/arrow/expression.py
  vortex-python/python/vortex/dataset.py
  vortex-python/python/vortex/expr.py
  vortex-python/src/expr/mod.rs
Labels: feature

#4337 fix: Buffer<T> Clone bound
  vortex-buffer/src/buffer.rs
Labels: chore

#4338 feat: vortex-python/check.sh
  vortex-python/check.sh
Labels: feature

#4355 Revert "Re-open DuckDB context between iterations"
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/engines/ddb/mod.rs
Labels: fix

#4354 chore: revert to 20.04, enforce glibc version == 2.31
  .github/workflows/publish.yml
Labels: fix

#4175 feat: statistical and population genetics benchmark queries and dataset
  .github/workflows/sql-benchmarks.yml
  Cargo.lock
  Cargo.toml
  bench-vortex/Cargo.toml
  bench-vortex/src/bin/query_bench.rs
  bench-vortex/src/datasets/file.rs
  bench-vortex/src/datasets/mod.rs
  bench-vortex/src/engines/ddb/mod.rs
  bench-vortex/src/lib.rs
  bench-vortex/src/statpopgen/builder.rs
  bench-vortex/src/statpopgen/download_vcf.rs
  bench-vortex/src/statpopgen/mod.rs
  bench-vortex/src/statpopgen/schema.rs
  bench-vortex/src/statpopgen/statpopgen_benchmark.rs
  bench-vortex/src/statpopgen/vcf_conversion.rs
  bench-vortex/statpopgen.sql
Labels: feature

#4357 chore: update renovate.json
  renovate.json
Labels: chore

#4342 chore: Inline arrow-pyarrow crate to avoid upstream pyo3 version pin
  Cargo.lock
  Cargo.toml
  vortex-python/Cargo.toml
  vortex-python/src/arrays/from_arrow.rs
  vortex-python/src/arrays/mod.rs
  vortex-python/src/arrow.rs
  vortex-python/src/dataset.rs
  vortex-python/src/dtype/mod.rs
  vortex-python/src/file.rs
  vortex-python/src/io.rs
  vortex-python/src/iter/mod.rs
  vortex-python/src/lib.rs
Labels: chore

#4359 feat: show statpopgen benchmarks
  benchmarks-website/config.js
  benchmarks-website/data-processor.js
  benchmarks-website/data-shared.js
  benchmarks-website/data-worker.js
  benchmarks-website/index.html
  benchmarks-website/scoring.js
  benchmarks-website/worker-manager.js
Labels: feature

#4362 Re-open DuckDB context between iterations (take 2)
  .github/workflows/ci.yml
  bench-vortex/src/benchmark_driver.rs
  bench-vortex/src/engines/ddb/mod.rs
Labels: do not merge, chore

#4366 chore: exclude vortex-error from coverage report
  .github/workflows/ci.yml
Labels: chore

#4367 fix: Always use setSafe when writing values from spark
  java/vortex-spark/src/main/java/dev/vortex/spark/write/VortexDataWriter.java
Labels: fix

#4369 fix[vortex-datafusion]: add filename context on read error
  vortex-datafusion/src/persistent/opener.rs
Labels: fix

#4371 Feature: Add `DType::FixedSizeList` variant
  encodings/sparse/src/canonical.rs
  fuzz/src/array/compare.rs
  fuzz/src/array/filter.rs
  fuzz/src/array/search_sorted.rs
  fuzz/src/array/slice.rs
  fuzz/src/array/sort.rs
  fuzz/src/array/take.rs
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/arrays/constant/canonical.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
  vortex-array/src/canonical.rs
  vortex-array/src/compute/conformance/cast.rs
  vortex-array/src/compute/conformance/consistency.rs
  vortex-datafusion/src/convert/scalars.rs
  vortex-dtype/src/arbitrary.rs
  vortex-dtype/src/arrow.rs
  vortex-dtype/src/dtype.rs
  vortex-dtype/src/field.rs
  vortex-dtype/src/serde/flatbuffers/mod.rs
  vortex-dtype/src/serde/proto.rs
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-ffi/src/dtype.rs
  vortex-jni/src/dtype.rs
  vortex-python/src/dtype/mod.rs
  vortex-python/src/python_repr.rs
  vortex-python/src/scalar/into_py.rs
  vortex-python/src/scalar/mod.rs
  vortex-scalar/src/arbitrary/mod.rs
  vortex-scalar/src/arrow/mod.rs
  vortex-scalar/src/display.rs
  vortex-scalar/src/list.rs
  vortex-scalar/src/null.rs
  vortex-scalar/src/scalar.rs
  vortex-scalar/src/tests/core.rs
Labels: feature

#4380 Feature: Add `FixedSizeList` support in `vortex-scalar`
  vortex-scalar/src/list.rs
  vortex-scalar/src/scalar.rs
  vortex-scalar/src/tests/casting.rs
  vortex-scalar/src/tests/core.rs
  vortex-scalar/src/tests/mod.rs
  vortex-scalar/src/tests/nested.rs
  vortex-scalar/src/tests/nullability.rs
  vortex-scalar/src/tests/primitives.rs
Labels: feature

#4377 Remove old redundent display function in the fuzzer
  fuzz/src/error.rs
Labels: chore

#4352 fix: don't recursively dictionary-encode dictionary codes
  fuzz/fuzz_targets/array_ops.rs
  fuzz/src/array/mod.rs
  vortex-btrblocks/src/lib.rs
  vortex-file/src/strategy.rs
  vortex-file/src/tests.rs
  vortex-layout/src/layouts/compressed.rs
  vortex-layout/src/layouts/dict/writer/mod.rs
  vortex-python/src/compress.rs
  vortex/src/lib.rs
  wasm-test/src/main.rs
Labels: fix

#4384 fix: Add downcasts for dict codes and runend ends
  vortex-btrblocks/src/float.rs
  vortex-btrblocks/src/integer.rs
Labels: fix

#4392 fix: ubuntu uses dash which lacks pipefail
  .github/workflows/publish.yml
Labels: fix

#4385 Feature: `FixedSizeList` infrastructure
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/builders/list.rs
  vortex-datafusion/src/convert/scalars.rs
  vortex-dtype/src/arbitrary.rs
  vortex-dtype/src/serde/flatbuffers/mod.rs
  vortex-dtype/src/serde/proto.rs
  vortex-flatbuffers/flatbuffers/vortex-dtype/dtype.fbs
  vortex-flatbuffers/src/generated/dtype.rs
  vortex-flatbuffers/src/generated/message.rs
  vortex-proto/Cargo.toml
  vortex-proto/README.md
  vortex-proto/proto/dtype.proto
  vortex-proto/src/generated/vortex.dtype.rs
  vortex-scalar/src/arrow/mod.rs
Labels: feature

#4390 fix[vortex-array]: propagate preferred type conversion to nested fields
  docs/guides/python-integrations.md
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-layout/src/layouts/dict/reader.rs
  vortex-python/python/vortex/arrays.py
Labels: fix

#4407 feat: Add BitOrd and Concat for `Mask`
  vortex-mask/src/bitops.rs
  vortex-mask/src/lib.rs
  vortex-mask/src/tests.rs
Labels: feature

#4413 Chore: rename bad todos
  vortex-dtype/src/field.rs
  vortex-scalar/src/arrow/mod.rs
  vortex-scalar/src/scalar.rs
Labels: chore

#4410 Chore: Rename `TimeUnit` variants to be more descriptive
  encodings/datetime-parts/src/canonical.rs
  encodings/datetime-parts/src/compress.rs
  encodings/datetime-parts/src/compute/cast.rs
  encodings/datetime-parts/src/compute/compare.rs
  encodings/datetime-parts/src/compute/filter.rs
  encodings/datetime-parts/src/compute/mod.rs
  encodings/datetime-parts/src/compute/take.rs
  encodings/datetime-parts/src/timestamp.rs
  vortex-array/src/arrays/datetime/mod.rs
  vortex-array/src/arrays/datetime/test.rs
  vortex-array/src/arrays/extension/compute/cast.rs
  vortex-array/src/arrow/compute/to_arrow/temporal.rs
  vortex-array/src/arrow/convert.rs
  vortex-datafusion/src/convert/scalars.rs
  vortex-dtype/src/datetime/arrow.rs
  vortex-dtype/src/datetime/temporal.rs
  vortex-dtype/src/datetime/unit.rs
  vortex-duckdb/src/convert/dtype.rs
  vortex-duckdb/src/convert/scalar.rs
  vortex-duckdb/src/exporter/temporal.rs
  vortex-jni/src/dtype.rs
  vortex-scalar/src/arrow/mod.rs
  vortex-scalar/src/arrow/tests.rs
  vortex-scalar/src/display.rs
Labels: chore

#4416 feat: teach Patches to fast-path search sorted on primitive array
  vortex-array/src/patches.rs
Labels: feature

#4396 chore: remove gradle inferred processors and update gradle jvm links
  java/build.gradle.kts
  java/gradle/gradle-daemon-jvm.properties
  java/settings.gradle.kts
Labels: chore

#4405 Feature: Add `FixedSizeListArray` and `FixedSizeListVTable`
  vortex-array/src/arrays/fixed_size_list/mod.rs
  vortex-array/src/arrays/fixed_size_list/tests/basic.rs
  vortex-array/src/arrays/fixed_size_list/tests/degenerate.rs
  vortex-array/src/arrays/fixed_size_list/tests/mod.rs
  vortex-array/src/arrays/fixed_size_list/tests/nested.rs
  vortex-array/src/arrays/fixed_size_list/tests/nullability.rs
  vortex-array/src/arrays/fixed_size_list/vtable/array.rs
  vortex-array/src/arrays/fixed_size_list/vtable/canonical.rs
  vortex-array/src/arrays/fixed_size_list/vtable/mod.rs
  vortex-array/src/arrays/fixed_size_list/vtable/operations.rs
  vortex-array/src/arrays/fixed_size_list/vtable/serde.rs
  vortex-array/src/arrays/fixed_size_list/vtable/validity.rs
  vortex-array/src/arrays/fixed_size_list/vtable/visitor.rs
  vortex-array/src/arrays/mod.rs
  vortex-array/src/arrow/compute/to_arrow/canonical.rs
  vortex-array/src/canonical.rs
  vortex-array/src/compute/conformance/cast.rs
  vortex-array/src/compute/conformance/consistency.rs
  vortex-array/src/validity.rs
  vortex-btrblocks/src/lib.rs
  vortex-duckdb/src/exporter/mod.rs
Labels: feature

#4399 feat: prepared scan: accelerate successive range reads to a file
  vortex-scan/src/lib.rs
Labels: feature

#4428 Feature: Add `FixedSizeListBuilder`
  vortex-array/src/arrays/fixed_size_list/tests/basic.rs
  vortex-array/src/arrays/fixed_size_list/tests/nested.rs
  vortex-array/src/arrays/fixed_size_list/tests/nullability.rs
  vortex-array/src/builders/fixed_size_list.rs
  vortex-array/src/builders/list.rs
  vortex-array/src/builders/mod.rs
Labels: feature

#4435 Chore: Validate `Scalar::new` for null and clean up `DecimalScalar`
  vortex-array/src/builders/list.rs
  vortex-scalar/src/binary.rs
  vortex-scalar/src/bool.rs
  vortex-scalar/src/decimal/macros.rs
  vortex-scalar/src/decimal/mod.rs
  vortex-scalar/src/decimal/scalar.rs
  vortex-scalar/src/decimal/value.rs
  vortex-scalar/src/extension.rs
  vortex-scalar/src/list.rs
  vortex-scalar/src/primitive.rs
  vortex-scalar/src/proto.rs
  vortex-scalar/src/scalar.rs
  vortex-scalar/src/struct_.rs
  vortex-scalar/src/utf8.rs
Labels: chore

#4425 chore: `GetItem` to apply parent nullability
  vortex-expr/src/exprs/get_item.rs
Labels: chore

#4447 Chore: Remove `append_scalar_value`
  vortex-array/src/arrays/arbitrary.rs
  vortex-array/src/builders/mod.rs
Labels: chore
